### ISSUE TITLE
Problem after update to 18.10.3

### ISSUE THREAD

**Issue by wackou72** [centreon/centreon#7272] opened 2019-03-12 15:25 UTC
<h1>BUG REPORT INFORMATION </h1>

<h3> Prerequisites </h3>

***Versions***

centreon-engine-18.10.0-4.el7.centos.x86_64
centreon-widget-live-top10-memory-usage-18.10.0-6.el7.centos.noarch
centreon-plugin-Applications-Databases-Mysql-20190221-145606.el7.centos.noarch
centreon-widget-live-top10-cpu-usage-18.10.0-6.el7.centos.noarch
centreon-plugin-Hardware-Ups-Standard-Rfc1628-Snmp-20190221-145606.el7.centos.noarch
centreon-clib-18.10.0-2.el7.centos.x86_64
centreon-plugin-Applications-Monitoring-Centreon-Database-20190221-145606.el7.centos.noarch
centreon-release-18.10-2.el7.centos.noarch
centreon-connector-18.10.0-2.el7.centos.x86_64
centreon-common-18.10.3-5.el7.centos.noarch
centreon-widget-servicegroup-monitoring-18.10.0-6.el7.centos.noarch
centreon-plugin-Network-Cisco-Standard-Snmp-20190221-145606.el7.centos.noarch
centreon-broker-storage-18.10.1-1.el7.centos.x86_64
centreon-pp-manager-18.10.4-1.el7.centos.noarch
centreon-engine-daemon-18.10.0-4.el7.centos.x86_64
centreon-widget-hostgroup-monitoring-18.10.0-6.el7.centos.noarch
centreon-widget-service-monitoring-18.10.0-11.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ftp-20190221-145606.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ldap-20190221-145606.el7.centos.noarch
centreon-plugin-Operatingsystems-Windows-Snmp-20190221-145606.el7.centos.noarch
centreon-database-18.10.3-5.el7.centos.noarch
centreon-license-manager-18.10.2-1.el7.centos.noarch
centreon-broker-cbmod-18.10.1-1.el7.centos.x86_64
centreon-18.10.3-5.el7.centos.noarch
centreon-plugin-Virtualization-Vmware2-Connector-Plugin-20190221-145606.el7.centos.noarch
centreon-plugins-base-1.18-2.el7.centos.noarch
centreon-widget-grid-map-18.10.0-6.el7.centos.noarch
centreon-trap-18.10.3-5.el7.centos.noarch
centreon-widget-host-monitoring-18.10.0-11.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Central-20190221-145606.el7.centos.noarch
centreon-widget-engine-status-18.10.0-9.el7.centos.noarch
centreon-broker-18.10.1-1.el7.centos.x86_64
centreon-plugin-Applications-Protocol-Http-20190221-145606.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Map4-Jmx-20190221-145606.el7.centos.noarch
centreon-plugin-Hardware-Printers-Generic-Snmp-20190221-145606.el7.centos.noarch
centreon-poller-centreon-engine-18.10.3-5.el7.centos.noarch
centreon-base-config-centreon-engine-18.10.3-5.el7.centos.noarch
centreon-connector-ssh-18.10.0-2.el7.centos.x86_64
centreon-connector-perl-18.10.0-2.el7.centos.x86_64
centreon-perl-libs-18.10.3-5.el7.centos.noarch
centreon-widget-tactical-overview-18.10.0-6.el7.centos.noarch
centreon-plugin-Applications-Protocol-Dns-20190221-145606.el7.centos.noarch
centreon-license-manager-common-18.10.2-1.el7.centos.noarch
centreon-broker-core-18.10.1-1.el7.centos.x86_64
centreon-web-18.10.3-5.el7.centos.noarch
centreon-broker-cbd-18.10.1-1.el7.centos.x86_64
centreon-engine-extcommands-18.10.0-4.el7.centos.x86_64
centreon-widget-graph-monitoring-18.10.0-6.el7.centos.noarch
centreon-plugin-Operatingsystems-Linux-Snmp-20190221-145606.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Poller-20190221-145606.el7.centos.noarch
centreon-plugin-Virtualization-VMWare-daemon-3.0.0-20190221161610.el7.centos.noarch

***Operating System***

CentOS Linux release 7.6.1810 (Core)

VM on ESXi

<h3> Description </h3>

When viewing the list of services or host, using the drop-down menu to acknowledge or Schedule Immediate Check, this do nothing

<h3> Steps to Reproduce </h3>

Please describe precisely the steps to reproduce the encountered issue.

1. I logged in Centreon
2. I reached the Services view
3. I select a service to acknowledge
4. I click on the drop-down menu and click on Services : Acknowledge
5. Pop-Up appear to fill the acknowledge information, then click on Acknowledge selected problems

<h3> Describe the received result </h3>
Service is not acknowledge
<h3> Describe the expected result </h3>
Service need to be acknowledge
<h3> Additional relevant information (e.g. frequency, ...) </h3>
I try on different browser and with the Private Mode, same result.
THe whole drop-down menu seems broken.

**Comment by adr-mo** [comment] 2019-03-12 18:51
Hi @wackou72,

Thanks for the feedback 👍 

**Could you please check a few things.**

First thing first could you check that centcore service is running ?
`systemctl status centcore`

If it is started, could try this ?

- Open a SSH session on the Central Server and display centreon engine logs.
`tailf /var/log/centreon-engine/centengine.log`
- Try to set an acknowledgement using the web user interface.
Can you see in the logs any log starting with `ACKNOWLEDGE_SVC_PROBLEM ` ?

If there is no logs related to the ACK could try this ?

Try to set an acknowledgement using the web user interface.
- Open a SSH session on the Central Server and display php error logs
`tailf var/opt/rh/rh-php71/log/php-fpm/centreon-error.log` and lookup for **errors**

- Open the **developers tool** (on chrome for example **F12**) and check that there is no JavaScript related errors.

Regards,

**Comment by wackou72** [comment] 2019-03-13 07:29
Hello :)

`systemctl status centcore`
● centcore.service - Centreon Core
   Loaded: loaded (/usr/lib/systemd/system/centcore.service; enabled; vendor preset: disabled)
   Active: inactive (dead)

Then I do a `systemctl start centcore`

`systemctl status centcore`
● centcore.service - Centreon Core
   Loaded: loaded (/usr/lib/systemd/system/centcore.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2019-03-13 08:27:13 CET; 1s ago
 Main PID: 7768 (centcore)
   CGroup: /system.slice/centcore.service
           └─7768 /usr/bin/perl /usr/share/centreon/bin/centcore

If I reboot the system, centcore didn't start

Have a nice day
Regards

**Comment by adr-mo** [comment] 2019-03-13 07:47
````
``Hi` @wackou72 

The issue with centcore that does not start on boot depends on how you install your Centreon Central Server. Currently we have an issue with the OVF on that subject that will be fixed soon :)

For now you can do
`systemctl enable centcore`

This will enable the service on boot time machine.

Let me know if you still encounter the issue.

Regards,

**Comment by wackou72** [comment] 2019-03-13 08:00
I built a new server with your ISO and then migrate from 3.4 to 18.10 by using your procedure.
Nothing exotic on the system.
`systemctl enable centcore` do nothing
I made `systemctl disable centcore` and then again `systemctl enable centcore`
_Created symlink from /etc/systemd/system/centreon.service.wants/centcore.service to /usr/lib/systemd/system/centcore.service._

**Comment by adr-mo** [comment] 2019-03-13 08:19
Okay and problem was not solved ? centcore does not start on boot ?

Could you please start centcore and try to see the logs here https://github.com/centreon/centreon/issues/7272#issuecomment-472134818 so that we can confirm that the issue is not linked to the WUI :)

Thanks

**Comment by wackou72** [comment] 2019-03-13 08:33
So I start manually the centcore (systemctl start centcore)
Then acknowledge two services on the same host
```
tailf /var/log/centreon-engine/centengine.log
[1552465789] [4942] EXTERNAL COMMAND: ACKNOWLEDGE_SVC_PROBLEM;SRV_1;SERVICE_1;1;0;1;admin;Acknowledged by admin
[1552465789] [4942] EXTERNAL COMMAND: ACKNOWLEDGE_SVC_PROBLEM;SRV_1;SERVICE_2;1;0;1;admin;Acknowledged by admin
```

Thanks

**Comment by adr-mo** [comment] 2019-03-13 08:37
Awesome looks like it is **working now**.

May I close the issue ?

**Comment by wackou72** [comment] 2019-03-13 09:15
centcore is not working since last update, doesn't start.
will try to find out why.
you can close the ticket :)

**Closed** 2019-03-13 09:20 UTC
Labels: status/more-info-needed
