### ISSUE TITLE
Bug with new view "Ressources Status" for service linked to several hosts or by HG

### ISSUE THREAD

**Issue by TxX8N8LN** [centreon/centreon#9180] opened 2020-11-04 09:16 UTC
***Versions***
centreon-20.10.0-3.el7.centos.noarch
centreon-auto-discovery-server-20.10.0-2.el7.centos.noarch
centreon-base-config-centreon-engine-20.10.0-3.el7.centos.noarch
centreon-broker-20.10.0-7.el7.centos.x86_64
centreon-broker-cbd-20.10.0-7.el7.centos.x86_64
centreon-broker-cbmod-20.10.0-7.el7.centos.x86_64
centreon-broker-core-20.10.0-7.el7.centos.x86_64
centreon-broker-storage-20.10.0-7.el7.centos.x86_64
centreon-clib-20.10.0-2.el7.centos.x86_64
centreon-common-20.10.0-3.el7.centos.noarch
centreon-connector-20.10.0-2.el7.centos.x86_64
centreon-connector-perl-20.10.0-2.el7.centos.x86_64
centreon-connector-ssh-20.10.0-2.el7.centos.x86_64
centreon-database-20.10.0-3.el7.centos.noarch
centreon-engine-20.10.0-6.el7.centos.x86_64
centreon-engine-daemon-20.10.0-6.el7.centos.x86_64
centreon-engine-extcommands-20.10.0-6.el7.centos.x86_64
centreon-gorgone-20.10.0-14.el7.centos.noarch
centreon-gorgone-centreon-config-20.10.0-14.el7.centos.noarch
centreon-license-manager-20.10.0-1.el7.centos.noarch
centreon-license-manager-common-20.10.0-1.el7.centos.noarch
centreon-perl-libs-20.10.0-3.el7.centos.noarch
centreon-poller-centreon-engine-20.10.0-3.el7.centos.noarch
centreon-pp-manager-20.10.0-1.el7.centos.noarch
centreon-release-20.10-2.el7.centos.noarch
centreon-trap-20.10.0-3.el7.centos.noarch
centreon-web-20.10.0-3.el7.centos.noarch
centreon-widget-engine-status-20.10.0-5.el7.centos.noarch
centreon-widget-global-health-20.10.0-5.el7.centos.noarch
centreon-widget-graph-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-grid-map-20.10.0-5.el7.centos.noarch
centreon-widget-hostgroup-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-host-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-httploader-20.10.0-5.el7.centos.noarch
centreon-widget-live-top10-cpu-usage-20.10.0-5.el7.centos.noarch
centreon-widget-live-top10-memory-usage-20.10.0-5.el7.centos.noarch
centreon-widget-servicegroup-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-service-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-tactical-overview-20.10.0-5.el7.centos.noarch

***Browser used***

- [ X] Google Chrome
- [ X] Firefox

### Description
In the new view "Ressources Status"

If multiple "Hosts" have the same "Services", i have seen only one on the view, but when i use the deprecated view, i can see all.

See attach files.
![old](https://user-images.githubusercontent.com/59447936/98092184-afded780-1e86-11eb-99d3-ee31118a1d16.png)
![new](https://user-images.githubusercontent.com/59447936/98092188-b0776e00-1e86-11eb-9136-9a626c0df710.png)

Thanks for your return.

**Comment by cgagnaire** [comment] 2020-11-04 14:51
Or a "service by hostgroup" kind of service ?

**Comment by TxX8N8LN** [comment] 2020-11-04 15:41
Hi @cgagnaire , it's a service linked to those 2 hosts.
![service](https://user-images.githubusercontent.com/59447936/98132339-948ebf00-1ebc-11eb-895b-94fec9d81e5a.png)

**Comment by rousseaubenjamin** [comment] 2020-11-19 08:32
Hi same issue here
Exactly the same behavior.

**Comment by alenorcy** [comment] 2020-11-19 16:51
I have the same behavior (20.10 upgraded from 19.10).

**Comment by nicgef** [comment] 2020-11-20 14:50
*sorry for my English, I'm French...*

Hello,

I went from version 18.10 to version 20.10 this morning.
However, I am encountering a bug. On the first screen, showing the old interface, two of my Linux servers have their services in "Inconnu", which is normal for me because I have a problem on these servers (in short, that's not the subject).
On the other hand, on the second screen, showing the new interface, only one of the two appears with its unknown services. However, when I search for the second server, the services do appear with the status Inconnu.

I also have the same problem as TxX8N8LN: the number of issues does not match with what is displayed on the new interface.

Thank's 👍
![inconnus_services_details](https://user-images.githubusercontent.com/74780741/99813144-9c4e9480-2b47-11eb-9b93-df7310ac412b.png)
![inconnus_statut_ressources](https://user-images.githubusercontent.com/74780741/99813161-a1134880-2b47-11eb-9e51-59cddf4ece10.png)
![mismatch_new_interface](https://user-images.githubusercontent.com/74780741/99813499-0bc48400-2b48-11eb-8273-1299178bda23.png)

**Comment by reynolds-gre** [comment] 2020-11-24 14:36
> _**Versions**_
> centreon-20.10.0-3.el7.centos.noarch
> centreon-auto-discovery-server-20.10.0-2.el7.centos.noarch
> centreon-base-config-centreon-engine-20.10.0-3.el7.centos.noarch
> centreon-broker-20.10.0-7.el7.centos.x86_64
> centreon-broker-cbd-20.10.0-7.el7.centos.x86_64
> centreon-broker-cbmod-20.10.0-7.el7.centos.x86_64
> centreon-broker-core-20.10.0-7.el7.centos.x86_64
> centreon-broker-storage-20.10.0-7.el7.centos.x86_64
> centreon-clib-20.10.0-2.el7.centos.x86_64
> centreon-common-20.10.0-3.el7.centos.noarch
> centreon-connector-20.10.0-2.el7.centos.x86_64
> centreon-connector-perl-20.10.0-2.el7.centos.x86_64
> centreon-connector-ssh-20.10.0-2.el7.centos.x86_64
> centreon-database-20.10.0-3.el7.centos.noarch
> centreon-engine-20.10.0-6.el7.centos.x86_64
> centreon-engine-daemon-20.10.0-6.el7.centos.x86_64
> centreon-engine-extcommands-20.10.0-6.el7.centos.x86_64
> centreon-gorgone-20.10.0-14.el7.centos.noarch
> centreon-gorgone-centreon-config-20.10.0-14.el7.centos.noarch
> centreon-license-manager-20.10.0-1.el7.centos.noarch
> centreon-license-manager-common-20.10.0-1.el7.centos.noarch
> centreon-perl-libs-20.10.0-3.el7.centos.noarch
> centreon-poller-centreon-engine-20.10.0-3.el7.centos.noarch
> centreon-pp-manager-20.10.0-1.el7.centos.noarch
> centreon-release-20.10-2.el7.centos.noarch
> centreon-trap-20.10.0-3.el7.centos.noarch
> centreon-web-20.10.0-3.el7.centos.noarch
> centreon-widget-engine-status-20.10.0-5.el7.centos.noarch
> centreon-widget-global-health-20.10.0-5.el7.centos.noarch
> centreon-widget-graph-monitoring-20.10.0-5.el7.centos.noarch
> centreon-widget-grid-map-20.10.0-5.el7.centos.noarch
> centreon-widget-hostgroup-monitoring-20.10.0-5.el7.centos.noarch
> centreon-widget-host-monitoring-20.10.0-5.el7.centos.noarch
> centreon-widget-httploader-20.10.0-5.el7.centos.noarch
> centreon-widget-live-top10-cpu-usage-20.10.0-5.el7.centos.noarch
> centreon-widget-live-top10-memory-usage-20.10.0-5.el7.centos.noarch
> centreon-widget-servicegroup-monitoring-20.10.0-5.el7.centos.noarch
> centreon-widget-service-monitoring-20.10.0-5.el7.centos.noarch
> centreon-widget-tactical-overview-20.10.0-5.el7.centos.noarch
> 
> _**Browser used**_
> 
> * [ X] Google Chrome
> * [ X] Firefox
> 
> ### Description
> In the new view "Ressources Status"
> 
> If multiple "Hosts" have the same "Services", i have seen only one on the view, but when i use the deprecated view, i can see all.
> 
> See attach files.
> ![old](https://user-images.githubusercontent.com/59447936/98092184-afded780-1e86-11eb-99d3-ee31118a1d16.png)
> ![new](https://user-images.githubusercontent.com/59447936/98092188-b0776e00-1e86-11eb-9136-9a626c0df710.png)
> 
> Thanks for your return.



> I have the same behavior (20.10 upgraded from 19.10).

**Comment by reynolds-gre** [comment] 2020-11-24 14:40
Exactly the same issue after ugrading from 20.04 to 20.10

**Comment by alenorcy** [comment] 2020-11-30 17:23
> I have the same behavior (20.10 upgraded from 19.10).

it concerns services "by host" and services "by host group". Each service is only displayed once at most.

**Comment by alenorcy** [comment] 2020-12-23 09:12
Hello,
this problem is really very troublesome. Is this an anomaly that is present on all the installations or does it only appear after certain migrations? (for us it is about 20.10 upgraded from 19.10).

We have more than 700 hosts and more than 5000 services .. so it is not rare that several identical services are down and do not appear in the filters..the deprecated display works but it is less practical.

Thank you

**Comment by rousseaubenjamin** [comment] 2020-12-23 11:27
Same behavior on a fresh install on 20.10 @alenorcy (same behavior on 20.11)

**Comment by odric88** [comment] 2020-12-29 11:48
> Exactly the same issue after ugrading from 20.04 to 20.10

Idem, on CentOS 7. (1 server)

**Comment by joschi99** [comment] 2020-12-30 22:43
Same behavior after upgrade from Centreon 20.04.7 to 20.10.1 (CentOS 7)

**Comment by dellarte** [comment] 2021-01-11 10:07
Same behavior on a fresh install Centreon 20.10.1 Debian 10

**Comment by bouchbm** [comment] 2021-01-13 21:41
Same behavior after upgrade from 20.04 to 20.10

**Comment by Iralein** [comment] 2021-02-05 14:23
Same here for updated Centreon 20.10.2-7 on CentOS 7.

**Comment by dellarte** [comment] 2021-02-09 08:40
issue still present on Centreon 20.10.3

**Comment by zeph-gre** [comment] 2021-02-18 14:53
still the same issue with 20.10.3

**Comment by cgagnaire** [comment] 2021-02-23 14:09
We are working on it as I speak.

Refs: MON-6284

**Comment by lgigil** [comment] 2021-02-25 12:03
Same problem here with Centreon 20.10.3 (migrated from 19) on Centos 7

**Comment by dellarte** [comment] 2021-04-01 12:04
I was eager to find out if the problem is fixed in version 20.10.4, but still not.

**Comment by thnilsen** [comment] 2021-04-12 10:15
Still not fixed in 20.10.5 either. This is a major bug and ought to have received a lot more attention since it was reported 5 months ago. Any ETA on a fix?

**Comment by sbrizini** [comment] 2021-04-12 10:49
Hi,

Looking at the internal Jira, this issue has been fixed, tested and just cleared by QA. 
It is planned for the future 20.10.7 version.

As for the ETA, I'd bet on end of month (the major 21.04 being the main focus presently)

Cheers,
Sam

**Comment by heavenlyren** [comment] 2021-05-03 10:17
@sbrizini is this resolved in 21.04 ?

Tbh it's kind of weird that this bug was there for so long even though it's like the main page of the product that is broken...
We (The company I work for) are personally not using centreon anymore but I am personally curious about how this bug could've been left there for so long.

Is it documented anywhere that only the deprecated view work as intented ?

**Comment by sbrizini** [comment] 2021-05-03 11:50
Hi @heavenlyren 

It has indeed been solved in 21.04 as well. 
Regarding the question of why it took several months to solve the quick answer would be that although the apparent effect seems trivial (miscount of services) the underlying cause was rooted in the deep inner workings of our engine (what defines a service, can they ave identical IDs etc.). 
As you can imagine, solving this potentially impacted a lot of other components hence the added complexity.

Regarding documentation, it is now up to date and all deprecated functions should be now implemented within Resources Status.

Thx for you input,
Cheers,
Sam

**Closed by sbrizini** 2021-05-03 11:50 UTC
Labels: area/backend, area/monitoring, kind/bug
