### ISSUE TITLE
lvm option for centreon-backup-mysql.sh

### ISSUE THREAD

**Issue by gagzou** [centreon/centreon#8635] opened 2020-04-20 16:05 UTC
Hi,

I have a problem with LVM backups on ext4 :

[2020-04-17 10:07:01] Start database backup processus
Dumping Db with LVM snapshot (partial)
  Logical Volume "dbbackup" already exists in volume group "centos"
mount: mauvais type de système de fichiers, option erronée, superbloc erroné
        sur /dev/mapper/centos-dbbackup, page de code ou programme auxiliaire manquant, ou autre erreur

        Dans certains cas des renseignements utiles sont dans le journal
        système — essayez « dmesg | tail » ou quelque chose du genre.
Cannot backup with LVM snapshot. Maybe you can try with mysqldump

**dmesg:**
[75296.412106] EXT4-fs (dm-9): Unrecognized mount option "nouuid" or missing value

**In the centreon-backup-mysql.sh script, we have:
MNTOPTIONS = "- o nouuid"
This option is only available with XFS (not EXT4).**

centreon 19.10.10

**Comment by lpinsivy** [comment] 2020-04-23 11:55
Hi @gagzou thank you for your feedback

**Comment by sc979** [comment] 2020-06-04 12:42
Hi @gagzou ,
I'm currently working on this issue and will link the issue to the PR soon.
The internal ticket reference is MON-5566
Best regards

**Comment by sc979** [comment] 2020-06-04 14:08
The issue is introduced by the "nouuid" mount option, mandatory for 'XFS' partitions type.
The pull request in reference check the new temporary backup partition before launching the mount command.

**Comment by sc979** [comment] 2020-06-05 13:45
The modifications have been merged on master, 20.04, 19.10 and 19.04 branches.
And will be released as soon as possible

**Closed by sc979** 2020-06-05 13:45 UTC
Labels: area/backup, kind/bug, priority/major, status/accepted
