### ISSUE TITLE
Use Macros on Macros

### ISSUE THREAD

**Issue by nicutor** [centreon/centreon#3791] opened 2015-09-23 22:38 UTC
Hi,

Is there a way to add a MACRO on a host for example: MYSQL_PORT and then create a service and another MACRO on that service where to put $_HOSTMYSQL_PORT$ ?

I actually want to use an already defined macro on another macro value. 

Example:

1. On the host I will create this macro: CUSTOM_HOST_MACRO = value1
2. On any service connected with this host I want to create another macro: CUSTOM_SERVICE_MACRO = %CUSTOM_HOST_MACRO% and of course the value of CUSTOM_SERVICE_MACRO will be "value1"

If this is not possible, can you please consider as a new feature? This will save us a lot of time to define variables between services and hosts.

Thank you.

**Comment by julienmathis** [comment] 2015-09-24 09:36
@ganoze : I think you can help us :)

**Comment by ganoze** [comment] 2015-09-24 11:24
This is a duplicate of centreon/centreon-engine#1. This feature has not yet been implemented and is currently scheduled for the 2.x branch.

**Comment by nicutor** [comment] 2015-09-24 12:21
@ganoze will this work with nagios too? I am using nagios not centreon engine.

**Comment by ganoze** [comment] 2015-09-24 14:11
Nop this won't work with Nagios. This software does not support this kind of macro resolution.

**Comment by leoncx** [comment] 2015-09-28 10:06
Duplicate #318

**Closed** 2016-02-10 10:13 UTC
Labels: Kind/Enhancement, Status/Duplicate
