### ISSUE TITLE
ARG + MACROS now show up in the configuation

### ISSUE THREAD

**Issue by zskarman** [centreon/centreon#4810] opened 2016-12-02 16:22 UTC
--------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  2.8.1

When i Select the new command the command macros + args not visible on the UI.
Because I already setup an macro and arg as well.
This is works in 2.7.8 UI. - >2_7_8.png
![2_7_8](https://cloud.githubusercontent.com/assets/24320218/20841394/ed5e9a10-b8b3-11e6-8783-716571b57910.PNG)

URL:centreon/main.php?p=60206&o=c&service_id=xxx

![issue1](https://cloud.githubusercontent.com/assets/24320218/20841287/8dcaae22-b8b3-11e6-8299-8f79688433be.PNG)

Rgs, Zsolt

**Comment by zskarman** [comment] 2016-12-08 10:39
Guys,

could I get any comments on that bug?

**Comment by Sims24** [comment] 2016-12-08 10:41
Hi @zskarman , 

Could you copy/paste command definition of check_nt_cpu and check_nrpe please ?

**Comment by zskarman** [comment] 2016-12-08 10:43
$USER1$/check_nrpe -H $HOSTADDRESS$ $ARG1$
$USER1$/check_ping -H $HOSTADDRESS$ -t $ARG1$ -w $ARG2$ -c $ARG3$

**Comment by zskarman** [comment] 2016-12-08 10:54
I've checked again and it look the issue, is with only the ARG,
When change the command, the attached ARGs not shows in the UI.
But if I saved and back to the edit, i can see the args.

**Comment by ganoze** [comment] 2016-12-12 14:22
This is a duplicate of #4729.

**Closed by ganoze** 2016-12-12 14:22 UTC
Labels: Kind/Bug
