### ISSUE TITLE
Recurrent downtimes - error period 1

### ISSUE THREAD

**Issue by jakefoster2018** [centreon/centreon#7485] opened 2019-04-25 07:52 UTC
<h1>BUG REPORT INFORMATION </h1>

<h3> Prerequisites </h3>

***Versions***
centreon-base-config-centreon-engine-18.10.4-9.el7.centos.noarch
centreon-widget-graph-monitoring-18.10.0-6.el7.centos.noarch
centreon-database-18.10.4-9.el7.centos.noarch
centreon-common-18.10.4-9.el7.centos.noarch
centreon-plugin-Applications-Protocol-Dns-20190412-141630.el7.centos.noarch
centreon-pp-manager-18.10.4-1.el7.centos.noarch
centreon-engine-18.10.0-4.el7.centos.x86_64
centreon-release-18.10-2.el7.centos.noarch
centreon-widget-global-health-18.10.0-8.el7.centos.noarch
centreon-widget-engine-status-18.10.0-9.el7.centos.noarch
centreon-connector-perl-18.10.0-2.el7.centos.x86_64
centreon-plugin-Applications-Monitoring-Centreon-Map4-Jmx-20190412-141630.el7.centos.noarch
centreon-plugin-Operatingsystems-Linux-Snmp-20190412-141630.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Database-20190412-141630.el7.centos.noarch
centreon-license-manager-18.10.2-1.el7.centos.noarch
centreon-widget-service-monitoring-18.10.2-1.el7.centos.noarch
centreon-connector-ssh-18.10.0-2.el7.centos.x86_64
centreon-plugin-Operatingsystems-Windows-Snmp-20190412-141630.el7.centos.noarch
centreon-plugin-Hardware-Printers-Generic-Snmp-20190412-141630.el7.centos.noarch
centreon-plugin-Network-Cisco-Standard-Snmp-20190412-141630.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Poller-20190412-141630.el7.centos.noarch
centreon-plugin-Applications-Databases-Mysql-20190412-141630.el7.centos.noarch
centreon-widget-live-top10-memory-usage-18.10.0-6.el7.centos.noarch
centreon-widget-tactical-overview-18.10.0-6.el7.centos.noarch
centreon-broker-storage-18.10.1-1.el7.centos.x86_64
centreon-plugin-Applications-Protocol-Ldap-20190412-141630.el7.centos.noarch
centreon-web-18.10.4-9.el7.centos.noarch
centreon-widget-host-monitoring-18.10.1-1.el7.centos.noarch
centreon-engine-daemon-18.10.0-4.el7.centos.x86_64
centreon-plugin-Applications-Monitoring-Centreon-Central-20190412-141630.el7.centos.noarch
centreon-perl-libs-18.10.4-9.el7.centos.noarch
centreon-plugin-Hardware-Ups-Standard-Rfc1628-Snmp-20190412-141630.el7.centos.noarch
centreon-broker-cbmod-18.10.1-1.el7.centos.x86_64
centreon-widget-httploader-18.10.0-6.el7.centos.noarch
centreon-widget-live-top10-cpu-usage-18.10.0-6.el7.centos.noarch
centreon-broker-core-18.10.1-1.el7.centos.x86_64
centreon-poller-centreon-engine-18.10.4-9.el7.centos.noarch
centreon-engine-extcommands-18.10.0-4.el7.centos.x86_64
centreon-broker-cbd-18.10.1-1.el7.centos.x86_64
centreon-widget-grid-map-18.10.0-6.el7.centos.noarch
centreon-widget-servicegroup-monitoring-18.10.0-6.el7.centos.noarch
centreon-connector-18.10.0-2.el7.centos.x86_64
centreon-license-manager-common-18.10.2-1.el7.centos.noarch
centreon-plugin-Applications-Protocol-Http-20190412-141630.el7.centos.noarch
centreon-18.10.4-9.el7.centos.noarch
centreon-clib-18.10.0-2.el7.centos.x86_64
centreon-widget-hostgroup-monitoring-18.10.0-6.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ftp-20190412-141630.el7.centos.noarch
centreon-broker-18.10.1-1.el7.centos.x86_64
centreon-trap-18.10.4-9.el7.centos.noarch

<h3> Description </h3>

I am unable to  set re-occurring downtimes from PM hrs till AM hrs?.  
I need to set re-occurring downtime from 21:00 to 07:30 the next day - but i cant do it as the re-occurring downtime errors with 'Error Period 1'  
I can set one downtime window from 00:00 -> 07:30, but when i try to set the first downtime window (21:00 -> 00:00) it errors, the only way i can get round it is to set the first downtime window to be 21:00 -> 23:59, which leaves 1 minute of non-downtime and i get notifications in that one minute

**Comment by adr-mo** [comment] 2019-04-25 19:01
Hi @jakefoster2018,

Thanks for the feedback :100: 

We are currently working on this issue :+1: 

Related issues:
- https://github.com/centreon/centreon/issues/7337
- https://github.com/centreon/centreon/issues/5963

Regards,

**Comment by jakefoster2018** [comment] 2019-04-29 09:41
That's great, when can we expect a fix please?

**Comment by adr-mo** [comment] 2019-04-29 09:47
Hi @jakefoster2018 

This will be available soon hopefuly.

This issue is kind of **tricky**.

What I can ensure you is that it should be available for the next releases
- 19.04.1
- 18.10.5

Regards,

**Comment by jakefoster2018** [comment] 2019-06-25 16:35
Hi there, is this meant to be fixed in 18.10.5 as i've upgrade to that and its still an issue? 'error period 1'

**Comment by joschi99** [comment] 2020-04-17 12:34
Are there some news about this issue? We have the same problem using Centreon 19.10.10. Some workaround or hotfix available?

**Comment by JuliusKoenig** [comment] 2020-05-27 15:58
Issue is still in 20.04.2. Are there some news about this?

**Comment by joschi99** [comment] 2022-07-08 07:35
the issue is still open. Is there any solution available?

**Comment by ponchoh** [comment] 2022-07-08 13:07
Being that all the versions discussed here have reached their EOL, I will close this case. 

https://docs.centreon.com/docs/releases/lifecycle/

- Several updates to downtimes > 20.04.2 https://docs.centreon.com/docs/20.04/releases/centreon-core/#20043
- propose all to update to a recent release
  - https://docs.centreon.com/docs/upgrade/introduction/

# 😊⛱

**Closed by ponchoh** 2022-07-08 13:07 UTC
Labels: kind/bug, status/in-backlog

**Comment by JuliusKoenig** [comment] 2022-07-08 14:34
Okay then I would like to bring this back to life :)

I have just recreated the above problem in a current version 22.04.0. Unfortunately it is still not possible to schedule a weekly downtime from for example 9 pm. to 2 am.

Here are a few screenshots:
 
![image](https://user-images.githubusercontent.com/8570502/178012628-c4f8a551-0a47-40b5-8821-e36f1a27bc0f.png)
_here it works_


![image](https://user-images.githubusercontent.com/8570502/178012830-43894c46-ff6f-4703-8485-1e081d08a391.png)
_and as you can see here, the error "Error period 1" occurs._

**Comment by joschi99** [comment] 2022-07-08 14:51
I can confirm that the problem is still there on any supportet version, please reopen the case.

**Comment by ponchoh** [comment] 2022-07-08 15:03
Thank you for this @joschi99 and @JuliusKoenig let me look into this and I will get back to you.

**Comment by ponchoh** [comment] 2022-07-08 21:02
Have you tried with a multi period?

![image](https://user-images.githubusercontent.com/85764737/178069762-4355873f-f410-4512-8dfc-12e4dc2590ac.png)
![image](https://user-images.githubusercontent.com/85764737/178069786-cdb1f779-20ff-405b-9380-0d6bb6f1f831.png)

**Comment by joschi99** [comment] 2022-07-11 05:58
Yes, we configured 2 periods, one until 23:59 and the second from 00:00. But as described 1 minute between 23:59 and 0:00 will not covered from the downtime and alarms are send in this time range

**Comment by ponchoh** [comment] 2022-07-11 13:18
I see now, we need to use 24 and actually type it.

![image](https://user-images.githubusercontent.com/85764737/178272895-6eee1dac-5634-473c-bb4a-25ea01574521.png)

**Comment by bambin401** [comment] 2022-11-02 14:01
Hello, the issue is still existing in version 21.04.20, is there any news on fixing the issue ?
