### ISSUE TITLE
[18.10.2] Problem login by LDAP

### ISSUE THREAD

**Issue by leandroschatts** [centreon/centreon#7134] opened 2019-01-16 13:09 UTC
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:   18.10.2

**Centreon Engine version**:   18.10.0

**Centreon Broker version**: 18.10.0

**OS**: CentOS 7

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VMware

**Steps to reproduce the issue:**

1. Configure your Centreon to login by LDAP;
2.  Try Login with your User and Pass LDAP;
3. Very Slow to logon.

**Describe the results you received:**

After the migration to 18.10, is too slow to login by LDAP.

In sql-error.log  shows these infinite errors:
2019-01-16 10:41|0|0| QUERY : SELECT contact_id FROM contact
                        WHERE contact_ldap_dn IN ()
2019-01-16 10:41|0|0| QUERY : SELECT contact_id FROM contact
                        WHERE contact_ldap_dn IN ()
2019-01-16 10:41|0|0| QUERY : SELECT contact_id FROM contact
                        WHERE contact_ldap_dn IN ()
2019-01-16 10:41|0|0| QUERY : SELECT contact_id FROM contact
                        WHERE contact_ldap_dn IN ()
2019-01-16 10:41|0|0| QUERY : SELECT contact_id FROM contact
                        WHERE contact_ldap_dn IN ()

In ldap.log show all is ok:
2019-01-16 10:40|-1|0|0|LDAP AUTH : OK, let's go !
2019-01-16 10:40|-1|0|0|LDAP AUTH : Update user DN for user teste_leandro

In centAct.log show these:

PHP Warning:  ldap_read(): Search: No such object in /usr/share/centreon/www/class/centreonLDAP.class.php on line 408

In LdapSearch.log show these:

[16/01/2019 10:36]LDAP Search : Filter : (&(samAccountName=*)(objectClass=user)(samAccountType=805306368))
[16/01/2019 10:36]LDAP Search : Size Limit : 35000
[16/01/2019 10:36]LDAP Search : Timeout : 60
[16/01/2019 10:36]LDAP Search : Error : Success
[16/01/2019 10:36]LDAP Search : 39 entries found
[16/01/2019 10:36]LDAP Search : 39
[16/01/2019 10:18] LDAP Search : XML Output :
[16/01/2019 10:37]LDAP Connect : trying url : ldap://x.x.x.x:389/
[16/01/2019 10:37]LDAP Connect : Credentials : sa_nagios
[16/01/2019 10:37]LDAP Connect : Credentials : sa_nagios
[16/01/2019 10:37]LDAP Connect : trying url : ldap://x.x.x.x:389/
[16/01/2019 10:37]LDAP Connect : Credentials : sa_nagios
[16/01/2019 10:40]LDAP Connect : trying url : ldap://x.x.x.x::389/
[16/01/2019 10:40]LDAP Connect : Credentials : sa_nagios
[16/01/2019 10:40]LDAP Connect : Credentials : sa_nagios
[16/01/2019 10:40]LDAP Connect : trying url : ldap://x.x.x.x::389/
[16/01/2019 10:40]LDAP Connect : Credentials : sa_nagios

**Describe the results you expected:**

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment] 2019-01-18 14:21
Do you use v2 or v3 protocol version?

**Comment by leandroschatts** [comment] 2019-01-24 15:57
Hello,
I use version 2, but I tested both.

**Comment by JonBogan** [comment] 2019-01-25 17:44
Same versions with same problem.  Issue appears to be the query:

    2019-01-25 12:41|0|0| QUERY : SELECT contact_id FROM contact
                        WHERE contact_ldap_dn IN ()

**Comment by leandroschatts** [comment] 2019-01-29 17:43
Hello,
I created a new server through the OVF Template, made the new settings, and even then it is giving the same error in SQL-error.log.

The login works, but it takes a few seconds to login.

**Comment by JonBogan** [comment] 2019-01-29 18:41
The problem is the inordinate amount of time it takes

    $cgs = new CentreonContactgroup($this->pearDB);
    $cgs->syncWithLdap();

to run.  This is found in both `www/class/centreonAuth.LDAP.class.php` and `www/include/configuration/configGenerate/xml/generateFiles.php`.

The length of time is proportional to the number of LDAP members and groups.  Maybe the LDAP sync should be moved to a less impactful process.

**Comment by leandroschatts** [comment] 2019-01-29 19:03
Has there been any source code change from the previous version to 18.10 in the LDAP part?
Because in the previous version it worked normally.

**Comment by JonBogan** [comment] 2019-01-29 19:11
`syncWithLdap()` is defined in `www/class/centreonAuth.LDAP.class.php`.  It was last updated on Jun 20, 2018 with #6370 .

**Comment by leandroschatts** [comment] 2019-01-30 16:27
If you want some log I can attach here.

**Comment by leandroschatts** [comment] 2019-02-20 16:52
Hello,
I has 7105 objects users on my Active Directory, Can i change the ldap search for better performance?

**Comment by leandroschatts** [comment] 2019-03-27 13:48
Hello
I upgrade to last version and the problem continues.

+ Centreon Web: 18.10.4
+ Centreon Engine: 18.10.0
+ Centreon Broker: 18.10.1

**Comment by Gspaz** [comment] 2019-04-15 14:52
Hello,

Same issue using centreon web 18.10.4-9.

Very slow to logon and sql-error.log displays lots of :
```
QUERY : SELECT contact_id FROM contact
                        WHERE contact_ldap_dn IN ()
```

LDAP auth not usuable with this bug.

Thank you

**Comment by chatshine** [comment] 2019-04-24 08:30
Hello i have de same problem, slow logon, export configuration very slow ans sql-error.log displays lot of:

`QUERY : SELECT contact_id FROM contact
                        WHERE contact_ldap_dn IN ()`

Centreon Web 18.10.4

**Comment by phips209** [comment] 2019-04-25 12:00
Same problem here 😞 
Centreon Web 18.10.4

A lot of errors in sql-error.log:
`2019-04-23 10:24|0|0| QUERY : SELECT contact_id FROM contact

php-fpm consumes high cpu load at user login.

2000 users in AD.

**Comment by adr-mo** [comment] 2019-04-30 13:55
Hi,

This issue will be fixed in the **18.10.5**.

Fixed by this PR https://github.com/centreon/centreon/pull/7278

Regards,

**Comment by adr-mo** [comment] 2019-04-30 13:55
Linked to https://github.com/centreon/centreon/issues/6969

**Comment by leandroschatts** [comment] 2019-05-10 17:42
Hello @adr-mo this problem will be fix on version 19.04 too?

**Comment by adr-mo** [comment] 2019-05-10 17:44
Hi @leandroschatts 

Sure. Any fixes made on 18.10.x versions will be cherry-picked on master (19.04.x)

Regards

**Comment by sebastien-ggp** [comment] 2019-05-22 20:05
Hello, 

I have exactly the same problem in version 19.04.0 on a new installation since the iso

Centreon Web version: 19.04.0

OS: CentOS 7 , Fresh install from iso

Steps to reproduce the issue:

Configure your Centreon to login by LDAP;
User imported from Ldap;
Try Login with your User and Pass LDAP;
Very Slow to logon.


[root@centreon]# tail login.log
2019-05-22 21:50|-1|0|0|[WEB] No contact found with this login : ''
[root@centreon]# tail ldap.log
2019-05-22 21:50|-1|0|0|Connexion = CN=Admin xxxx Sebastien,OU=Admins,OU=Utilisateurs,OU=xxxxxxx,DC=domain,DC=loc :: Success
2019-05-22 21:50|-1|0|0|LDAP AUTH : OK, let's go !
2019-05-22 21:50|-1|0|0|LDAP AUTH : Update user DN for user admxxxxx

[22/05/2019 21:50]LDAP Connect : Credentials : domain\centreon
[22/05/2019 21:50]LDAP Connect : Credentials : domain\centreon
[22/05/2019 21:50]LDAP Connect : trying url : ldap://ldap-domain.loc:389/
[22/05/2019 21:50]LDAP Connect : Credentials : domain\serv_056centreon
[22/05/2019 21:50]LDAP Connect : trying url : ldap://ldap-domain.loc:389/

Thank you in advance

**Comment by sebastien-ggp** [comment] 2019-05-22 20:06
Hello,

I have exactly the same problem in version 19.04.0 on a new installation since the iso

Centreon Web version: 19.04.0

OS: CentOS 7 , Fresh install from iso

Steps to reproduce the issue:

Configure your Centreon to login by LDAP;
User imported from Ldap;
Try Login with your User and Pass LDAP;
Very Slow to logon.

[root@centreon]# tail login.log
2019-05-22 21:50|-1|0|0|[WEB] No contact found with this login : ''
[root@centreon]# tail ldap.log
2019-05-22 21:50|-1|0|0|Connexion = CN=Admin xxxx Sebastien,OU=Admins,OU=Utilisateurs,OU=xxxxxxx,DC=domain,DC=loc :: Success
2019-05-22 21:50|-1|0|0|LDAP AUTH : OK, let's go !
2019-05-22 21:50|-1|0|0|LDAP AUTH : Update user DN for user admxxxxx

[22/05/2019 21:50]LDAP Connect : Credentials : domain\centreon
[22/05/2019 21:50]LDAP Connect : Credentials : domain\centreon
[22/05/2019 21:50]LDAP Connect : trying url : ldap://ldap-domain.loc:389/
[22/05/2019 21:50]LDAP Connect : Credentials : domain\centreon
[22/05/2019 21:50]LDAP Connect : trying url : ldap://ldap-domain.loc:389/

Thank you in advance

**Comment by adr-mo** [comment] 2019-05-27 19:45
Hi @leandroschatts @sebastien-ggp 

This issue is currently being fixed by our developers.

It should be ready for the **19.10.2 and 18.10.6**

Regards

**Comment by Gspaz** [comment] 2019-05-28 14:10
> 
> 
> Hi @leandroschatts @sebastien-ggp
> 
> This issue is currently being fixed by our developers.
> 
> It should be ready for the **19.10.2 and 18.10.6**
> 
> Regards

Hi

19.04.X will be fixed too ?

Thank you

**Comment by adr-mo** [comment] 2019-05-28 14:13
Sorry I meant 19.04.2

Regards,

**Comment by Gspaz** [comment] 2019-05-28 14:16
Ok perfect :)
thank you

**Comment by Moujimouja** [comment] 2020-08-17 14:45
Hi, 

Versions 19.04.2  & 18.10.6 have been released for a while so I close this ticket cause it's probably not relevant anymore. If you still encounter the issue, feel free to re-open it.

**Closed by Moujimouja** 2020-08-17 14:45 UTC
Labels: kind/bug
