### ISSUE TITLE
[enhancement] Link one/several host templates to one hostgroup

### ISSUE THREAD

**Issue by Sims24** [centreon/centreon#4544] opened 2016-07-21 13:00 UTC
Hi, 

Would be a nice enhancement to have the ability to link one (or more) host template to an hostgroup. 

When adding an host to the hostgroup, the host will automatically inherits from host templates associated with this hostgroup (and its linked service templates).

That would be much more efficient to configure host in the same fashion, and that could probably help to remove or definitely stop "services linked to hostgroup" functionnality that is clearly not a best practices. 

Think could be related to https://github.com/centreon/centreon/issues/2532 , just asking if there is any news or review on this recently ? 

Thanks !

Simon

**Comment by lpinsivy** [comment] 2017-09-08 14:31
duplicate of #4655

**Closed by lpinsivy** 2017-09-08 14:31 UTC
Labels: kind/enhancement
