### ISSUE TITLE
Realtime downtime Scheduling throug REST API

### ISSUE THREAD

**Issue by pierrick-openIT** [centreon/centreon#5387] opened 2017-06-28 10:29 UTC
Hi,
it should be usefull to schedule downtime in realtime from external scheduling tools. Somes big compagny use external scheduling tools to make operation on IT and actually only reccurent downtimes could be done trough REST API.

On a external application who execute a workflow, it's complicated and twisted to predict when the downtime will be execute.

Regards everyone.

**Comment by vincenteam44** [comment] 2017-08-14 10:25
Hi i've also created related issue #5192 
hope it will be added in next releases ;-)

**Comment by pierrick-openIT** [comment] 2017-08-14 11:41
i hope too ! ;)

**Comment by lpinsivy** [comment] 2017-08-24 12:13
Duplicate of #5192

**Closed by lpinsivy** 2017-08-24 12:13 UTC
Labels: area/api, kind/enhancement
