### ISSUE TITLE
Contact group additive inheritance

### ISSUE THREAD

**Issue by ponsn** [centreon/centreon#5933] opened 2017-11-29 15:15 UTC
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**Centreon**: 2.8.15
**Centreon-Engine**: centreon-engine-1.8.1-1.el7.centos.x86_64
**Centreon Broker version**: centreon-broker-core-3.0.11-1.el7.centos.x86_64
**OS**: RHEL 7.4 (Linux "hostname" 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 13 10:46:25 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux)

**Additional environment details (AWS, VirtualBox, physical, etc.):**
RHEL 7.4 with Qemu

**Steps to reproduce the issue:**
0. blank install of centreon
1. Create one contact group ContactGroupA, create userA, attach UserA to ContactGroupA
2. Create one contact group ContactGroupB, create userB, attach UserB to ContactGroupB
3. Create HostTemplateA, Attach ContactGroupA as notified contacts with notifications parms
4. Create HostTemplateB, define parent = HostTemplateA
5. Create ServiceA (checking one snmp oid), attach ServiceA to ServiceTemplateA, 
6. Attach ServiceTemplateA to HostTemplateB
7. Create HostA, attach to HostTemplateB, define ContactGroupB as local notified contacts, check the Contract Group additive inheritance
8. reload configuration
9. make the checked oid fail
10. wait for the service to fail, and the notifications to be sent out. 

**Describe the results you received:**
Only ContactGroupB (directly attached to HostA) people receive the notifications, ContactGroupA (attached to HostTemplateA) are not notified, but both groups are visible in the Monitoring > Status Details > Host > HostA > Host information > Notifications > Contact groups notified for this host field.

**Describe the results you expected:**
Both ContactGroupA and ContactGroupB should be notified. 

**Additional information you think important (e.g. issue happens only occasionally):**
Swapping users between ContactGroups have the expected effect (UserB in ContactGroupA does not get notification, and the opposite).

**Comment by ponsn** [comment] 2017-11-29 15:28
![image](https://user-images.githubusercontent.com/18308770/33382862-c4d62008-d519-11e7-8c95-848ad18e1428.png)
For everyone's convience, i attach this quickly done sketch
One additional comment:
# If only ContactGroupA is there, it works, 
# If only ContactGroupB is there, it works as well.

**Comment by lpinsivy** [comment] 2018-01-26 13:02
Duplicate of #4869

**Closed by lpinsivy** 2018-01-26 13:02 UTC
