### ISSUE TITLE
[2.7.2] Multiple widget issues ?

### ISSUE THREAD

**Issue by gslongo** [centreon/centreon#4214] opened 2016-02-29 07:55 UTC
Dear team,

Here is a couple of bugs I'm facing to (browser cache cleaned).
1. No quick actions components anymore ??? (Acknowledge, re-check,...). I hope his is a bug..? The function is essential 
2. Host group monitoring is not working on Firefox... The widget is empty (Chrome is OK)

![capture-centreon - it network monitoring - mozilla firefox](https://cloud.githubusercontent.com/assets/5636906/13388649/07249ad4-dec2-11e5-99bb-9dab5f697ee8.png)

Thanks

**Comment by querwin** [comment] 2016-02-29 09:56
Hi,

1. Its a new enhancement. You can add it in options of your widget : "Display pagination and more actions".

2. I think it may be a know bug. Can you try to delete your widget and create it again ?

Regards,

**Comment by gslongo** [comment] 2016-02-29 10:47
Hi,

Thank you for your answer.

1. I don't see this option in widget options??? Attached
![capture-centreon - it network monitoring - mozilla firefox-1](https://cloud.githubusercontent.com/assets/5636906/13392330/008b43ae-deda-11e5-9bb4-f80b84ba70cf.png)

2. Re create the widget do not solve the issue. And as I said, it happens only on firefox 

Thanks !

**Comment by querwin** [comment] 2016-02-29 12:45
Did you updated your widgets in Administration > Extensions > Widgets ?

**Comment by gslongo** [comment] 2016-03-01 08:23
Dear Querwin,

Thank you for your answer. I did not updated the widgets, you arte true (sorry for that).
However, the initial bug is still present :

1. The widget is not properly displayed on Firefox

![capture-centreon - it network monitoring - mozilla firefox](https://cloud.githubusercontent.com/assets/5636906/13421518/1e42ff80-df8f-11e5-9051-7c6c4609a4cb.png)

2. The hostgroup and service group widget are still not OK on firefox

Thanks

**Comment by querwin** [comment] 2016-03-01 10:42
Hello,

Is it a CES Installation ?
Which version of the widget do you have ? 
Which version of Firefox ?

I think the problem is linked to the widgets and not to Centreon. So it will not be linked to the milestone.
We will create the ticket in the good project after.

**Comment by gslongo** [comment] 2016-03-01 11:00
I think I'm on the last CES (my server is up-to-date) 

```
[root@ces3 ~]# cat /etc/centos-release 
CentOS release 6.7 (Final)
```

My widget versions are :

> Graph Monitoring 	Widget for displaying RRD graphs 	1.3.0 
> Host Monitoring 	Widget for displaying host monitoring information 	1.4.2 
> Hostgroup Monitoring 	Widget for displaying hostgroup monitoring information 	1.3.0 
> Service Monitoring 	Widget for displaying service monitoring information 	1.4.2 
> Servicegroup Monitoring 	Widget for displaying servicegroup monitoring information 	1.3.0 

Firefox is 38.6.1 (ESR, latest)

Thanks

**Comment by querwin** [comment] 2016-03-01 12:53
Thanks

I think, you can try to update hostgroup and servicegroup widgets (last version is 1.3.1)

I think your problem with Firefox is linked to this issue : https://github.com/Centreon-Widgets/centreon-widget-service-monitoring/issues/28

**Comment by gslongo** [comment] 2016-03-01 13:19
Hi,

OK but it seems there is no stable update for this widget in the RPM repository ? Are you sure it has been released ?

Thanks

**Comment by querwin** [comment] 2016-03-01 13:33
Oh you're right, my bad. You are using the good version.

I think all is linked to the ticket I talk to you before.

Is it possible for you to update your firefox ?

**Comment by gslongo** [comment] 2016-03-01 14:28
My Firefox is the latest ESR (Extended Support Release) and is up to date. Due to some restrictions we cannot use the mainline version

Thanks !

**Comment by gslongo** [comment] 2016-03-08 08:17
Any news on this ? 

Thanks !

**Comment by gslongo** [comment] 2016-03-16 15:58
Any news on this bug ?

Thank you

**Comment by julienmathis** [comment] 2017-03-01 13:14
Hello, 

Is this bug now fixed ? Sorry for the long delay.

**Closed** 2017-03-01 13:14 UTC
Labels: Kind/Question
