### ISSUE TITLE
[2.7.0-RC2]  External command for all services for this host doesn't work

### ISSUE THREAD

**Issue by Shini31** [centreon/centreon#3959] opened 2015-12-11 08:01 UTC
Hello,
External command "for all services for this host" doesn't work : 
 * Disable all service notifications on this host
 * Enable all service notifications on this host
 * Schedule an immediate check of all services on this host
 * Schedule an immediate check of all services on this host (forced)
 * Disable all service checks on this host
 * Enable all service checks on this host

These messages appears in error_log :

```
[Fri Dec 11 08:48:57 2015] [error] [client X.X.X.X] PHP Notice:  Trying to get property of non-object in /usr/share/centreon/www/class/centreonExternalCommand.class.php on line 115, referer: http://Y.Y.Y.Y/centreon/main.php?p=20202&o=hd&host_name=Centreon-Central
sh: -c: line 1: syntax error near unexpected token `newline'
sh: -c: line 1: `" >>'
```

Regards.

**Comment by Shini31** [comment] 2015-12-11 08:01
The same with "Schedule an immediate check of all services on this host (forced)" external command

**Comment by bsauveton** [comment] 2015-12-11 11:05
duplicate of 
https://github.com/centreon/centreon/issues/3952

**Closed by bsauveton** 2015-12-11 11:05 UTC
Labels: BetaTest, Kind/Bug, Status/Solved
