### ISSUE TITLE
Graph problem - On large interval

### ISSUE THREAD

**Issue by jben94** [centreon/centreon#6116] opened 2018-03-07 14:28 UTC
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.18

**Centreon Engine version**: 1.8.1

**Centreon Broker version**: 3.0.13

**OS**: RH 6.9

**Steps to reproduce the issue:**
1. Go to Performance
2. Choose a graph, which takes the number of users connected to a wifi terminal for example.
3. Change the time interval

**Describe the results you received:**

We have a problem with the displayed values, which are related to the number of rows retrieved during an 'xport rrdtool'.

The displayed values should be the warning limit, first horizontal line

![image](https://user-images.githubusercontent.com/16583698/37096283-747d2560-2218-11e8-898f-0a8971d086fd.png)

![image](https://user-images.githubusercontent.com/16583698/37096302-85f5e700-2218-11e8-8aa7-105d1e2c5171.png)

**Describe the results you expected:**

![image](https://user-images.githubusercontent.com/16583698/37096392-bfa28210-2218-11e8-9784-8d70ead83244.png)

![image](https://user-images.githubusercontent.com/16583698/37096416-cef5fcce-2218-11e8-912a-c477447f3469.png)

**Comment by lpinsivy** [comment] 2018-03-15 09:29
Duplicate of #5996

**Comment by jben94** [comment] 2018-03-15 09:52
Hi @lpinsivy 
It's not the same subject!
Can you reopen this incident

**Comment by cgagnaire** [comment] 2020-07-31 15:59
Fixed by @garnier-quentin when refactoring graph backend since 19.10.x serie.

**Closed by cgagnaire** 2020-07-31 15:59 UTC
Labels: status/duplicate
