### ISSUE TITLE
CLAPI configuration export is missing command Argument Descriptions

### ISSUE THREAD

**Issue by btassite** [centreon/centreon#6320] opened 2018-05-29 12:22 UTC
Centreon version 2.8.22
Centreon Engine 1.8.1
Centreon Broker 3.0.14

CLAPI configuration export is missing command Argument Descriptions.
Consequently, service templates etc. show "ARG1" "ARG2" etc. for Argument Descriptions after import.

**Comment by lpinsivy** [comment] 2018-05-29 13:46
duplicate of #4220

**Closed by lpinsivy** 2018-05-29 13:46 UTC
