### ISSUE TITLE
BUG : Not possible to change display limit page in Supervision Page from Administration Page

### ISSUE THREAD

**Issue by MaxCentreon** [centreon/centreon#6507] opened 2018-08-01 11:28 UTC
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.24

**Centreon Engine version**: 1.8.1

**Centreon Broker version**: 3.0.13

**OS**: CentOS 7

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.
Setup :  Administration -> Centreon Web -> Limite par page (par défaut) : 100
2.
Go to : Supervision -> Details Status -> Look the display limit page
3.

**Describe the results you received:**
The first time you go to this page , it s working, but if you go severals times, it keeps the limit page by default at 30

**Describe the results you expected:**
 it take the limit page by default at 100

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment] 2018-08-21 12:08
duplicate of #6325

**Closed by lpinsivy** 2018-08-21 12:08 UTC
