### ISSUE TITLE
[2.8.18] Reload/Restart Configuration Failed due to SQL Deadlock

### ISSUE THREAD

**Issue by Crash-Fox** [centreon/centreon#6307] opened 2018-05-28 07:06 UTC
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.19

**Centreon Engine version**: 1.8.1

**OS**: CentOS 6.9

**Additional environment details (AWS, VirtualBox, physical, etc.):**
We have currently 6 pollers
The repartition of hosts/services is very different from each of them:

Collector 1: 644 Hosts
Collector 2: 92 Hosts
Collector 3: 1366 Hosts
Collector 4: 194 Hosts
Collector 5: 128 Hosts
Collector 6: 1502 Hosts

We use MySQL 5.6.20

And we have on the centreon_storage database:

More than 5 billion entries into the database centreon_storage
Database length: 338 GBits

**Steps to reproduce the issue:**
1. Go to Configuration --> Poller --> Export configuration
2. Select one or more collectors
3. Select "Deplacer les fichiers générés" and "Redémarrer l'ordonnanceur"
4. Click on the Export button

**Describe the results you received:**
After few seconds, the error SQLSTATE[40001]: Serialization Failure: 1213 Deadlock found ... [file:/usr/share/centreon/www/class/config-generate/generate.class.php] [line: 112] is displayed.

**Describe the results you expected:**
It shouldn't appeared and we shouldn't have to continuosly restart this process (for exporting and reloading/restarting the configuration on collectors) until no Deadlock error appeared.

**Additional information you think important (e.g. issue happens only occasionally):**
Please find attached to this ticket the show full processlist output 
[show_full_processlist.txt](https://github.com/centreon/centreon/files/2044027/show_full_processlist.txt)

**Comment by lpinsivy** [comment] 2018-05-29 11:36
Duplicate of #6192

**Closed by lpinsivy** 2018-05-29 11:36 UTC
