### ISSUE TITLE
Menu Rules not found in Configuration/Notifications/ after installed centreon-open-tickets

### ISSUE THREAD

**Issue by McklRgt** [centreon/centreon#8669] opened 2020-04-29 15:10 UTC
OS : CentOS 7
MariaDB

Centreon 18.10.12
centreon-open-tickets 20.04.0

After installing centreon-open-tickets, I should find Rules in Configuration / Notifications to add new rule and continue to parameter the open-tickets object. 
Do you know why and how to solve this problem ?

**Comment by lpinsivy** [comment] 2020-05-07 12:14
Duplicate of #8668

**Closed by lpinsivy** 2020-05-07 12:14 UTC
Labels: status/duplicate
