### ISSUE TITLE
[Bug] Display problem with Meta_Service and ACL Users

### ISSUE THREAD

**Issue by bmareau** [centreon/centreon#6396] opened 2018-06-22 12:48 UTC
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**Centreon Web version**: 2.8.23
**Centreon Engine version**: 1.8.1
**Centreon Broker version**: 3.0.14

**Steps to reproduce the issue:**
1. Create user with ACLs (All ressources = All services / All hosts / All meta_services)
2. Create a meta_service
3. Export Conf / Reload ACLs
4. Connect with this user 
5. You can see this meta_service in "Configuration - Services - Meta_Services"
6. You can't see this meta_service in "Monitoring - Services"

**Describe the results you received:**
You can see this meta_service in "Configuration - Services - Meta_Services"
You can't see this meta_service in "Monitoring - Services"

**Describe the results you expected:**
We should see meta_service in "Monitoring - Services" page

Regards

**Comment by Moujimouja** [comment] 2020-06-05 16:02
Hi,

Thanks for your feedback, I can't reproduce on 19.10.x & 20.04.x.

I close this issue.

**Closed by Moujimouja** 2020-06-05 16:02 UTC
Labels: area/acl, area/configuration, area/monitoring, kind/bug, priority/minor
