### ISSUE TITLE
Custom check command, template and service

### ISSUE THREAD

**Issue by kabreu** [centreon/centreon#7121] opened 2019-01-10 16:43 UTC
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
18.10.2

**Centreon Engine version**: 
centreon-engine-18.10.0

**Centreon Broker version**: 
centreon-broker-cbd-18.10.1

**OS**: 
CentOS7

**Steps to reproduce the issue:**
1. Create a check command with custom macros.
2. Create a template with the newly created check command.
3. Create a service with the newly created template.

**Describe the results you received:**
The macros are not appearing in the web interface for the new services when you select your template

**Describe the results you expected:**
Macros appears when you select your template

**Additional information you think important (e.g. issue happens only occasionally):**
If you add a centreon created template to the template you create, all the macros now appears in the interface when you select this template for your service (the macros from the centreon template and the macros from the custom one you created)

**Comment by lpinsivy** [comment] 2019-01-18 14:14
can't reproduce.

Can you describe your command?

**Comment by cgagnaire** [comment] 2019-01-24 14:34
Hi @lpinsivy,
I can confirm that.
Something is going wrong in the getMacros function of centreonService.class.php.
It doesn't go to the latest template.
You can test it with the "generic-passive-service-custom" that will not show you the two dummy macros (base-generic >= 3.2.0).
Works fine for host by the way.

**Comment by joschi99** [comment] 2019-03-20 17:14
Same situation is on version 18.10.3
Macros on Service Checks will not shown, macros from Host Checks are shown correctly. Any news about this case?

**Comment by adr-mo** [comment] 2019-04-30 13:25
Hi,

This will be fixed in **18.10.x and 19.04.x versions**

Regards,

**Comment by s-duret** [comment] 2019-05-10 13:37
Hi,
Please open this case, the patch doesn't work.
My configuration is the following:
service -> template 1 -> template 2
If you add you check command on template 2 and defined values for macros on this template, you can't see them on the service...

**Comment by s-duret** [comment] 2019-05-14 09:52
Hi,
It works!
Thanks

**Closed** 2019-05-14 12:44 UTC
Labels: kind/bug
