### ISSUE TITLE
Custom Views - Shared/Public Views are write-protected

### ISSUE THREAD

**Issue by itsul** [centreon/centreon#6472] opened 2018-07-16 15:43 UTC
When you mark a Custom View as Public, or share it with other users, it starts to become write-protected, even for the creator. If you remove the allowed users again, you can't edit the view. Currently you need to create a new view and delete the "protected" one.

I'm expecting that the creator is able to make changes on a Custom View, even if it is shared or public.

This occurs within the complete 2.8.x branch
centreon-engine-1.8.1-1.el7.centos.x86_64
centreon-broker-core-3.0.14-1.el7.centos.x86_64
centreon-web-2.8.24-1.el7.centos.noarch

**Comment by Moujimouja** [comment] 2020-08-17 12:39
Hi,

Tested on the latest Centreon version, can't reproduce.

I close this issue.

**Closed by Moujimouja** 2020-08-17 12:39 UTC
Labels: area/custom-views, kind/bug, priority/minor
