### ISSUE TITLE
[2.8.14] - removing a host template deletes the services from the host

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon#5788] opened 2017-10-13 19:39 UTC
**Centreon Web version**:  2.8.14

**Centreon Engine version**:  1.8.0

**Centreon Broker version**: 3.0.10

**OS**:  CentOS 6.9

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VMWare

**Steps to reproduce the issue:**
1. create a new host using one or more host templates
2. export configuration to poller (with templates added by the host template)
3. remove one host template from the host
4. export configuration to poller

**Describe the results you received:**
you have a host without services

**Describe the results you expected:**
the services for this host are still there

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment] 2018-01-26 13:00
duplicate of #4371

**Closed by lpinsivy** 2018-01-26 13:00 UTC
