### ISSUE TITLE
Add "externalcmd.so" directive by default

### ISSUE THREAD

**Issue by Eldertoon** [centreon/centreon#5589] opened 2017-08-24 09:07 UTC
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.11
**Centreon Engine version**: 
1.7.2-3
**Centreon Broker version**: 
3.0.8-1
**OS**: 
CentOS 6 / CES 3.4
**Additional environment details (AWS, VirtualBox, physical, etc.):**
Both machines are VM in VMWare 6

**Steps to reproduce the issue:**
1. I go in Monitoring->Status Details
2. I check any services were the host is defined on my satellite poller (Managed From)
3. I choose "Services : Schedule immediate check" or "Services : Schedule immediate check (Forced)"

**Describe the results you received:**
I wait about 2~3 minutes : no update

**Describe the results you expected:**
An updated status.
If at step 2. I choose a server managed from Central, I'll receive an update in less than 30s (Last Check column display a small amount of time)

**Additional information you think important (e.g. issue happens only occasionally):**
This is a brand new satellite poller. I have no issue to push configuration on it with the web interface. Checks can't be forced but are working normally (I just can't force them). I tried to look at engine configuration : two are active, the one for central and the one for my poller module. I already check parameters to have them identical. I restarted both VM. I don't find any log when I schedule an immediate check, that would help if you can tell me where to look.

**Comment by lpinsivy** [comment] 2017-08-29 15:15
Hi,

Can you use the following command on your distant poller:
# tailf /var/log/centreon-engine/centengine.log | grep SCHEDULE

And try to reschedule checks from Centren web interface.

You must have entries like:
[1504019642] [27255] EXTERNAL COMMAND: SCHEDULE_SVC_CHECK;srv-oracle-crm;oracle-buffer-hit-ratio;1504019641

Can you confirm?

**Comment by Eldertoon** [comment] 2017-08-30 11:42
Hi,

Thank you for the log name. I can confirm : nothing is displayed with the satellite poller
[root@mna-nagios ~]# tail -f /var/log/centreon-engine/centengine.log | grep SCHEDULE

And I see the request on the local poller :
[root@calimero service]# tail -f /var/log/centreon-engine/centengine.log | grep SCHEDULE
[1504093041] [9171] EXTERNAL COMMAND: SCHEDULE_FORCED_SVC_CHECK;a8770;HTTP;1504093041

Also I discovered I can't schedule service downtime on the satellite poller while it works well on the local one. This is definetely a communication issue when using the web interface ?

Regards,

**Comment by Eldertoon** [comment] 2017-08-30 11:54
Also I created a service alert on the satellite poller and the log is OK :
[1504093683] [21342] SERVICE ALERT: epdeventc1;EVENTVIEWER;UNKNOWN;SOFT;1;Client - ERROR: File not found: C:/administration/eventc/travail/epdeventc1.csv

**Comment by lpinsivy** [comment] 2017-09-05 11:17
Hi,

You should have a problem with centcore process. This process allow to export configuration files to the poller and export command from Centreon web interface.

Can you try to:

- Be sure that this process is running
- Try to restart it
- control /var/log/centreon/centcore.log file for errors

Regards,

**Comment by Eldertoon** [comment] 2017-09-05 11:59
Hi,

A simple correction : export of config files works well (I added new server and they are monitored). Only downtime + force check are failing.

Process is ru

- nning
- Restarted without success, all servers are restarted once a week so everything already has been restarted since opening this
- I found something in this log :
`2017-08-24 10:12:54 - Could not write into pipe file /var/lib/centreon-engine/rw/centengine.cmd on poller 2`

I confirm on my second poller : files doesn't exist. On the central poller, file exist and is owned by centreon-engine. I checked every rights on the previous folder and they are the same both side. Stopping centreon-engine make the file disappear on Central and reappear by restarting. Nothing happen on remote when restarting.

Both /etc/centreon-engine/centengine.cfg cointains the line
`command_file=/var/lib/centreon-engine/rw/centengine.cmd`

I have seen that central engine configuration contains in Data->Multiple broker module :
```
/usr/lib64/centreon-engine/externalcmd.so
/usr/lib64/nagios/cbmod.so /etc/centreon-broker/central-module.xml
```

Satelite poller engine contains at the same place :
`/usr/lib64/nagios/cbmod.so /etc/centreon-broker/poller-module.xml`

I suppose something fishy here. Any idea ?

Regards,

**Comment by lpinsivy** [comment] 2017-09-06 09:54
You have this problem because you have an error: "2017-08-24 10:12:54 - Could not write into pipe file /var/lib/centreon-engine/rw/centengine.cmd on poller 2"

Can you stop centengine on poller 2, delete  /var/lib/centreon-engine/rw/centengine.cmd and start centengine process.

Do you have script which insert external commands into  /var/lib/centreon-engine/rw/centengine.cmd?

Regards,

**Comment by Eldertoon** [comment] 2017-09-06 10:06
Hi,

As said : folder is empty and permission / ownership already checked on parent folders. Everything is OK and I have no error in logs. Conf indicates to create the file at this location with a buffer of 4096. I have restarted multiple times but nothing is created.

Regards,

**Comment by lpinsivy** [comment] 2017-09-06 11:06
Hi,

What is your centreon, centreon-engine and centreon-broker users and groups configuration on your poller 2?

**Comment by Eldertoon** [comment] 2017-09-08 15:22
On poller 2 / satellite poller :
```
[root@mna-nagios ~]# grep centreon /etc/passwd | sort
centreon-broker:x:496:496::/var/lib/centreon-broker:/bin/bash
centreon-engine:x:494:494::/var/lib/centreon-engine:/bin/bash
centreon:x:498:498::/var/spool/centreon:/bin/bash
[root@mna-nagios ~]# grep nagios /etc/passwd | sort
nagios:x:499:499::/var/spool/nagios:/bin/bash
[root@mna-nagios ~]# grep centreon /etc/group | sort
centreon-broker:x:496:centreon,nagios,centreon-engine
centreon-engine:x:494:centreon-broker,nagios,centreon
centreon:x:498:centreon-engine,centreon-broker
nagios:x:499:centreon-engine,centreon-broker
```

On Central :
```
[root@calimero ~]# grep centreon /etc/passwd | sort
centreon-broker:x:496:496::/var/spool/centreon-broker:/bin/bash
centreon-engine:x:494:494::/var/lib/centreon-engine:/bin/bash
centreon:x:498:498::/var/spool/centreon:/bin/bash
[root@calimero ~]# grep nagios /etc/passwd | sort
nagios:x:499:499::/home/nagios/:/bin/bash
[root@calimero ~]# grep centreon /etc/group | sort
apache:x:48:nagios,centreon
centreon-broker:x:496:centreon,nagios,centreon-engine,apache
centreon-engine:x:494:centreon-broker,apache,nagios,centreon
centreon:x:498:centreon-engine,centreon-broker,apache
nagios:x:499:centreon-engine,centreon-broker,apache
```

Everything is default as installed. Please note I've seen and installed an update :
**Centreon Web version:**
2.8.12

**Comment by itchytm** [comment] 2018-04-14 19:13
Hi Guys,
i am a newbie with centreon, just started monitoring with it a few weeks ago.
I have Monitored my Environment succesfully with the Central Engine.
But now i need a Poller for Monitoring Environments over a VPN.
So I need to get firm with the Centreon Poller. So i build an Environment in my local network with a Central and 1 Poller.
My First Test was with an Centreon Installation from the Repositories for EL7 ( EL7 Iso wasnt available) and the Poller too. I was sctrictly using the Documentation provided. 
But my Problem was the same like Eldertoon had. Immediate Checks (also forced) doesnt work.
I thought i did a mistake while the Install from the Repositories.
A few days ago i have seen that the EL7 ISO is out, so I decided to give it another try.
I strictly followed the actual Documentation provided for EL7 and have Set-Up again a Central and a Poller.
On the Central, everything is working fine, checks running, Immediate Checks working, all OK.
But on the Poller i have the Problem again. Checks are working without Problems, State of the Poller is running, Services are up and OK, but the "f*ing" Immediate Check still doesn't work.
I dont know where the problem is, i have readed every article i found about the problem, but no one of them really helps me. Not even a "maybe".
I am at a point where i can say the Problem is the Central, not the Poller, because:
When i "tcpdump" on the central i can see that nothing is sended from the Central to the Poller ( tcpdump on the Central Server). So there cant be a firewall ore something else issue.

I hope someone can help me with my Problem.
If u need logs or confs or something else, just ask.

Many thanks in advance

**Comment by Eldertoon** [comment] 2018-04-16 08:09
Hi,

Thank you for the comment, I'll do an update :

Centreon Web version:
2.8.21-7
Centreon Engine version:
1.8.1-1
Centreon Broker version:
3.0.14-1

I have now my main + 3 pollers. All react the same. My best guess now is some weird rights stuff. I suppose that when I update my poller and send the conf, some A user is used (and is well configured). When I try to force a check, I use some B user (and is not well configured). Also my best guess would be that this is linked to SSH keys / access to the pipe node. But yet I didn't found anything.

Regards,

**Comment by lpinsivy** [comment] 2018-04-30 14:47
Any error in /var/log/centreon/centcore.log ?

**Comment by itchytm** [comment] 2018-04-30 23:36
I have found a solution that worked for me.
There was a problem on my poller with one file.
I found in the centengine.log this error:

`Error: Could not create external command file '/var/lib/centreon-engine/rw/centengine.cmd' as named pipe: (17) -> File exists.  If this file already exists and you are sure that another copy of Centreon Engine is not running, you should delete this file.`

The file /var/lib/centreon-engine/rw/centengine.cmd was owned by centron.
After i renamed it and restarted the services, a new one was created, but this time owned by centreon-engine
and also marked as a pipe

After that correction all immediate checks working fine.

**Comment by Eldertoon** [comment] 2018-05-02 11:34
OK, that's the good lead I was needing ! The file centengine.cmd is not a pipe, it's a file and contains orders to poller.

In "/etc/rc.d/init.d/centengine", there is a $remove_command_file set to 1 which delete the pipe file at each stop, start and restart. When I start by hand the service, it doesn't create the pipe. Is this a setting ?

**Comment by lpinsivy** [comment] 2018-05-02 11:46
The file /var/lib/centreon-engine/rw/centengine.cmd sould be created by centengine during start process.

# ls -lah /var/lib/centreon-engine/rw/centengine.cmd
prw-rw---- 1 centreon-engine centreon-engine 0  2 mai   13:20 /var/lib/centreon-engine/rw/centengine.cmd

**Comment by Eldertoon** [comment] 2018-05-02 12:02
Yes, but no. It is created on my central, but no poller create it.

If I su as centreon-engine and do a mknod rw/centengine.cmd p it works

**Comment by lpinsivy** [comment] 2018-05-02 13:36
you right!!

**Comment by omercier** [comment] 2021-09-13 12:46
This has been fixed a while ago.
Thanks for your feedbacks!
Regards

**Closed by omercier** 2021-09-13 12:46 UTC
Labels: kind/enhancement, area/broker, area/configuration
