### ISSUE TITLE
Exception received : SQLSTATE[HY000] - Centreon 2.8.5

### ISSUE THREAD

**Issue by bgillon** [centreon/centreon#5165] opened 2017-04-18 23:41 UTC
Hello.
After upgrade from 2.8.4 to 2.8.5 on centos6.
Graph is not complete, and system is slow.
when i try to regenerate config file, i receive this error.

Preparing environment... OK
Generating files... NOK (Exception received : Exception received : SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction [file: /usr/share/centreon/www/class/config-generate/generate.class.php] [line: 117] )
Aborted.

No datas until upgrade.

**Comment by lpinsivy** [comment] 2017-04-20 15:47
Hi

Did you check process running on your MySQL server?

**Comment by bgillon** [comment] 2017-04-20 16:04
Hi.

Yes, and I can connect to Db by CLI

Regards,

Envoyé de mon iPhone

Le 20 avr. 2017 à 17:48, Laurent Pinsivy <notifications@github.com<mailto:notifications@github.com>> a écrit :


Hi

Did you check process running on your MySQL server?

**Comment by lpinsivy** [comment] 2017-09-08 08:17
Unable to reproduce, I close this issue

**Closed by lpinsivy** 2017-09-08 08:17 UTC
Labels: kind/question
