### ISSUE TITLE
Escalation - Configuration on Webinterface but not in escalation.cfg

### ISSUE THREAD

**Issue by FabulousRedPanda** [centreon/centreon#5510] opened 2017-08-03 16:53 UTC
##---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  2.8.11
**Centreon Engine version**:  1.7.2
**Centreon Broker version**:  3.0.8

**OS**: 
Distributor ID:	CentOS
Description:	CentOS Linux release 7.3.1611 (Core) 
Release:	7.3.1611
Codename:	Core

**Additional environment details (AWS, VirtualBox, physical, etc.):**
LXC 

**Steps to reproduce the issue:**
1.Escalation show on webinterface
2.Restart colector centrale
3.The escalation on the webinterface is not generate on /etc/centreon-engine/escalations.cfg unless we have only the header that notifiy the last modification

###################################################################
#                                                                 #
#         Last modification 2017-08-03 18:37                      #
###################################################################

**Describe the results you received:** 
Escalation didn't work because it's not generated on the file conf escalations.cfg

**Describe the results you expected:** 
We should see the configuration on escalation.cfg that we configure on the webinterface

#

**Comment by lpinsivy** [comment] 2017-08-04 11:55
I can't reproduce the problem:

1. Create escalation
2. Generate, test, move configuration and restart poller
3. File /etc/centreon-engine/escalations.cfg contains definition of escalation

**Comment by Sims24** [comment] 2017-08-04 12:08
hi @FabulousRedPanda

this is expected behaviour if you do not have any resource linked to your escalation. is this the case ?

**Comment by FabulousRedPanda** [comment] 2017-08-04 13:16
Yes, it's this case.
It can cause miss understanding maybe improvment is to force to add linked recources for add the escalation

**Comment by lpinsivy** [comment] 2017-08-04 14:53
I close this issue and I created an enhancement.

Regards

**Closed by lpinsivy** 2017-08-04 14:53 UTC
Labels: Status/Need more information
