### ISSUE TITLE
Centreon API missbehaving

### ISSUE THREAD

**Issue by hecko** [centreon/centreon#4127] opened 2016-01-20 16:53 UTC
Referencing #4047  but this is bugreport for 2.7.1 

We are experiencing slightly different issue - the configuration for poller is generated just fine with clapi

centreon -u clapi -p zxczxc -a APPLYCFG -v 12
they are generated with apache:apache owner flags
but the files are never moved to the poller

when generated via web page the files are generated and instantly moved to poller
in this case files are created as apache:centreon

groups:
centreon:x:498:centreon-engine,centreon-broker,apache

thats the only difference I see here that I can actually debug as I cant find ANY debug/log information about the process of generating files , copying to the pollers or restarting pollers in main centreon server

**Comment by julienmathis** [comment] 2016-02-25 17:27
Hello, 

Can you test the last 2.7.2. We have fixed some things arround CLAPI.

Thanks

**Comment by cemir** [comment] 2016-03-11 09:27
Hi,

in 2.7.2 i'ts not possible to generate the configuration :

`[loeulch@centreonfo-tk ~]# centreon -v
Centreon version 2.7.2 - Copyright Centreon - www.centreon.com
This software comes with ABSOLUTELY NO WARRANTY. This is free software,
and you are welcome to modify and redistribute it under the GPL license

usage: ./centreon -u <LOGIN> -p <PASSWORD> [-s] -o <OBJECT> -a <ACTION> [-v]
  -s 	Use SHA1 on password (default is MD5)
  -v 	variables 
  -h 	Print help 
  -V 	Print version 
  -o 	Object type 
  -a 	Launch action on Centreon
     Actions are the followings :
       - POLLERGENERATE: Build nagios configuration for a poller (poller id in -v parameters)
           #> ./centreon -u <LOGIN> -p <PASSWORD> -a POLLERGENERATE -v 1 
       - POLLERTEST: Test nagios configuration for a poller (poller id in -v parameters)
           #> ./centreon -u <LOGIN> -p <PASSWORD> -a POLLERTEST -v 1 
       - CFGMOVE: move nagios configuration for a poller to final directory (poller id in -v parameters)
           #> ./centreon -u <LOGIN> -p <PASSWORD> -a CFGMOVE -v 1 
       - POLLERRESTART: Restart a poller (poller id in -v parameters)
           #> ./centreon -u <LOGIN> -p <PASSWORD> -a POLLERRESTART -v 1 
       - POLLERRELOAD: Reload a poller (poller id in -v parameters)
           #> ./centreon -u <LOGIN> -p <PASSWORD> -a POLLERRELOAD -v 1 
       - POLLERLIST: list all pollers
           #> ./centreon -u <LOGIN> -p <PASSWORD> -a POLLERLIST

   For more information about configuration objects, please refer to CLAPI wiki:
      - http://documentation.centreon.com/docs/centreon-clapi/ 

Notes:
  - Actions can be written in lowercase chars
  - LOGIN and PASSWORD is an admin account of Centreon

[loeulch@centreonfo-tk ~]# centreon -u admin-sc -p testadminsc POLLERTEST -v 1
Unknown option
[loeulch@centreonfo-tk ~]# centreon -u admin-sc -p testadminsc -a POLLERTEST -v 1
OK: Nagios Poller 1 can restart without problem...
Return code end : 0
[loeulch@centreonfo-tk ~]# centreon -u admin-sc -p testadminsc -a POLLERRELOAD -v 1
centengine reload: done                                    [  OK  ]
Return code end : 0
[loeulch@centreonfo-tk ~]# centreon -u admin-sc -p testadminsc -a POLLERGENERATE -v 1
Please check that your parameters are valid
[loeulch@centreonfo-tk ~]# centreon -u admin-sc -p testadminsc -a APPLYCFG -v 1
2016-03-11 10:24:19 - APPLYCFG
Please check that your parameters are valid
`

**Comment by cemir** [comment] 2016-03-11 09:57
I just found it works as root, but only for the generation part :

sudo centreon -u admin-sc -p testadminsc -a APPLYCFG -v 1
2016-03-11 10:51:26 - APPLYCFG
Configuration files generated for poller '1'

root is not in the sudoers file.  This incident will be reported.

Return code end : 1

**Comment by cemir** [comment] 2016-03-11 10:01
here are the rights on the files :

sudo ls -l /usr/share/centreon/filesGeneration/nagiosCFG/1/
total 704
-rw-r--r-- 1 apache apache   3705 11 mar 10:53 centengine.cfg
-rw-r--r-- 1 apache apache  14503 11 mar 10:53 commands.cfg
-rw-r--r-- 1 apache apache   1412 11 mar 10:53 connectors.cfg
-rw-r--r-- 1 apache apache   1516 11 mar 10:53 contactgroups.cfg
-rw-r--r-- 1 apache apache   1729 11 mar 10:53 contacts.cfg
-rw-r--r-- 1 apache apache   1088 11 mar 10:53 dependencies.cfg
-rw-r--r-- 1 apache apache   1088 11 mar 10:53 escalations.cfg
-rw-r--r-- 1 apache apache   1752 11 mar 10:53 hostgroups.cfg
-rw-r--r-- 1 apache apache  66317 11 mar 10:53 hosts.cfg
-rw-r--r-- 1 apache apache   8551 11 mar 10:53 hostTemplates.cfg
-rw-r--r-- 1 apache apache   1428 11 mar 10:53 meta_commands.cfg
-rw-r--r-- 1 apache apache   1671 11 mar 10:53 meta_host.cfg
-rw-r--r-- 1 apache apache   2385 11 mar 10:53 meta_services.cfg
-rw-r--r-- 1 apache apache   1551 11 mar 10:53 meta_timeperiod.cfg
-rw-r--r-- 1 apache apache   4209 11 mar 10:53 nagiosCFG.DEBUG
-rw-r--r-- 1 apache apache   1276 11 mar 10:53 resource.cfg
-rw-r--r-- 1 apache apache   1438 11 mar 10:53 servicegroups.cfg
-rw-r--r-- 1 apache apache 528185 11 mar 10:53 services.cfg
-rw-r--r-- 1 apache apache  26622 11 mar 10:53 serviceTemplates.cfg
-rw-r--r-- 1 apache apache   1759 11 mar 10:53 timeperiods.cfg

**Comment by cemir** [comment] 2016-03-11 10:02
and the result of the move :

centreon -u admin-sc -p testadminsc -a CFGMOVE -v 1
PHP Warning:  chown(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 505
PHP Warning:  chgrp(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 506
PHP Warning:  chown(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 505
PHP Warning:  chgrp(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 506
PHP Warning:  chown(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 505
PHP Warning:  chgrp(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 506
PHP Warning:  chown(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 505
PHP Warning:  chgrp(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 506
PHP Warning:  chown(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 505
PHP Warning:  chgrp(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 506
PHP Warning:  chown(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 505
PHP Warning:  chgrp(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 506
PHP Warning:  chown(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 505
PHP Warning:  chgrp(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 506
PHP Warning:  chown(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 505
PHP Warning:  chgrp(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 506
PHP Warning:  chown(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 505
PHP Warning:  chgrp(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 506
PHP Warning:  chown(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 505
PHP Warning:  chgrp(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 506
PHP Warning:  chown(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 505
PHP Warning:  chgrp(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 506
PHP Warning:  chown(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 505
PHP Warning:  chgrp(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 506
PHP Warning:  chown(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 505
PHP Warning:  chgrp(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 506
PHP Warning:  chown(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 505
PHP Warning:  chgrp(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 506
PHP Warning:  chown(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 505
PHP Warning:  chgrp(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 506
PHP Warning:  chown(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 505
PHP Warning:  chgrp(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 506
PHP Warning:  chown(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 505
PHP Warning:  chgrp(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 506
PHP Warning:  chown(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 505
PHP Warning:  chgrp(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 506
PHP Warning:  chown(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 505
PHP Warning:  chgrp(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 506
PHP Warning:  chown(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 505
PHP Warning:  chgrp(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 506
PHP Warning:  chown(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 505
PHP Warning:  chgrp(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 506
PHP Warning:  chown(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 505
PHP Warning:  chgrp(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 506
PHP Warning:  chown(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 505
PHP Warning:  chgrp(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 506
PHP Warning:  chown(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 505
PHP Warning:  chgrp(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 506
PHP Warning:  chown(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 505
PHP Warning:  chgrp(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 506
PHP Warning:  chown(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 505
PHP Warning:  chgrp(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 506
PHP Warning:  chown(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 505
PHP Warning:  chgrp(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 506
PHP Warning:  chown(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 505
PHP Warning:  chgrp(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 506
PHP Warning:  chown(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 505
PHP Warning:  chgrp(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 506
PHP Warning:  chown(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 505
PHP Warning:  chgrp(): Operation not permitted in /usr/share/centreon/www/class/centreon-clapi/centreon.Config.Poller.class.php on line 506
OK: All configuration files copied with success.
Return code end : 0

**Comment by Dodofox** [comment] 2016-03-22 13:31
Hy everybody,

I'm sorry for my english. I had the same problem, I found a temporary solution until a patch a patch is deployed.

Every time you generate configuration file from web UI or with clapi, the directory named 1 (or 2 or 3 ...) is destroyed and rebuilt. if you make it with web ui, the rights given to the directory are apache centreon(rwx r-s ---) and if you make it with clapi, the rights are apache apache. 

Try to do "sudo chown apache:centreon /usr/share/centreon/filesGeneration/nagiosCFG/1" then execute APPLYCFG again.

**Comment by julienmathis** [comment] 2016-03-30 10:35
Will be fixed in 2.7.4.

**Comment by querwin** [comment] 2016-04-14 09:32
Hello,

I can't reproduce this problem. 

When I use root, all is OK.
When I use an other user but with sudo, is OK too.

Which user are you using to perform this tests ?

**Comment by mcajcd** [comment] 2016-05-24 12:58
Hi

same problem here with the lastest Centreon packages on Centos6.

Generation and apply pollers configuration is working inside the webui but if I use clapi with the APPLYCFG command, the files are generated on the central but never moved to the pollers.

When generating files in webui, permissions are:
-rw-r--r-- 1 apache centreon

When running clapi as root, permissions are:
-rw-r--r-- 1 apache apache

**Closed** 2016-07-04 14:10 UTC
Labels: Kind/Bug
