### ISSUE TITLE
Display problem when multiple graph are selected

### ISSUE THREAD

**Issue by tseegers** [centreon/centreon#6184] opened 2018-04-04 13:55 UTC
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.19
**Centreon Engine version**: 
1.7
**Centreon Broker version**: 
3
**OS**: 
Centreon 3.4

**Steps to reproduce the issue:**
1. Go to Monitoring  >  Performances  >  Graphs and select many graph (18 for example)

**Describe the results you received:**
The more graph you display, the more the problem is present. A white space is displaid on the page:

![capture1](https://user-images.githubusercontent.com/13485588/38311808-59bd47be-3820-11e8-8efc-3511a0924b80.PNG)

It creates also another problem, a gray period is displaid at the extreme right of the screen:

![image](https://user-images.githubusercontent.com/13485588/38311873-833a8854-3820-11e8-8ad1-3b8b18e384ba.png)

**Describe the results you expected:**

**Comment by lpinsivy** [comment] 2018-04-26 12:52
duplicate of #6133

**Closed by lpinsivy** 2018-04-26 12:52 UTC
