### ISSUE TITLE
[2.8.4] - Enhancement - Meta Services Resource Access

### ISSUE THREAD

**Issue by kozfelipe** [centreon/centreon#5045] opened 2017-03-01 18:28 UTC
---------------------------------------------------
Enhancement Request
---------------------------------------------------

Centreon Web 2.8.4-5
Centreon Engine 1.7.0
Centreon Broker 3.0.3
CentOS release 6.8 (Final)
MariaDB 5.5.53
CES VirtualBox

Everytime I create a new Meta Service I got to include it into ACL in order to grant acess to target users
I would like the same capability to include all hosts/hostgroups into ACL for Meta Services:

![image](https://cloud.githubusercontent.com/assets/25208457/23474514/c40f7cfe-fe92-11e6-9938-5e971cd81cbf.png)

Also, id like to know if there is a way to import Meta Services via CLAPI.

Thanks in Advance

**Comment by lpinsivy** [comment] 2017-08-24 13:21
Duplicate of #1938

**Closed by lpinsivy** 2017-08-24 13:21 UTC
Labels: area/api, kind/enhancement
