### ISSUE TITLE
Service ping is erase when you changing of host template

### ISSUE THREAD

**Issue by Tpo76** [centreon/centreon#5964] opened 2017-12-18 12:58 UTC
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.16
**Centreon Engine version**: 
1.8.1
**Centreon Broker version**: 
3.0.11
**OS**: 
el6 & el7
**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Add an host using 1 template for example OS-Linux-SNMP-custom
2. Edit host configuration of your host and change the template Ps-Linux-SNMP-custom with App-Monitoring-Centreon-Central-custom
3. Let "Create Services linked to the Template too" option to "No"
4. Go check your service for this host

**Describe the results you received:**
The service Ping has been delete

If you set "Create Services linked to the Template too" option to "yes", the Ping service is deleted and recreate. You can see that because sevice_id is not the same.

**Describe the results you expected:**
If the service ping already exist, don't do anything.
Because of this behavior you can't use any ping services in any module as BAM, MBI and MAP because everything using id to find your object.

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment] 2017-12-19 12:50
duplicate of #5788

**Closed by lpinsivy** 2017-12-19 12:50 UTC
