### ISSUE TITLE
Parameter Limit per page for Monitoring not applied on all pages of Monitoring Tab 

### ISSUE THREAD

**Issue by thiuyendang** [centreon/centreon#5557] opened 2017-08-18 12:56 UTC
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.12

**Centreon Engine version**: 

**Centreon Broker version**: 

**OS**: CentOS6, centOS7

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Go to Administration > Parameters > Centreon UI
2. Modify in Maximum page size section : Limit per page for Monitoring with a value different from the default value (30). Save. Logout and connect again (or empty cache)
3. Go to Monitoring > Status Details  > Services
4. Navigate on all pages all the Monitoring > Status details
5. Go back  to Monitoring > Status Details  > Services

**Describe the results you received:**
The limit per page turned back to the value of Limit per page (default).

**Describe the results you expected:**
Parameter Limit per page for Monitoring should be applied to all pages of Monitoring > Status details and should not be lost when we click on other pages.

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by Moujimouja** [comment] 2020-06-05 13:56
Hi,

Can't reproduce on 19.10.x version nor 20.04.x.

I close this ticket.

**Closed by Moujimouja** 2020-06-05 13:56 UTC
Labels: area/monitoring, kind/bug, priority/minor
