### ISSUE TITLE
[20.10] 404 not found after upgrade

### ISSUE THREAD

**Issue by BenoitPoulet** [centreon/centreon#9268] opened 2020-12-02 11:42 UTC
Not relevant

**Comment by adonix-dev** [comment] 2020-12-18 14:58
Same issue updating from 20.04 to 20.10 ...
![image](https://user-images.githubusercontent.com/31833518/102628413-eb3d1900-4149-11eb-9698-11c0b3206d18.png)

**Comment by adonix-dev** [comment] 2020-12-21 11:39
Resolved by changing _10-centreon.conf_
Adding that to _<Directory "/usr/share/centreon/www">_
`
RewriteRule ^index\.html$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.html [L]
ErrorDocument 404 /centreon/index.html
`

> Same issue updating from 20.04 to 20.10 ...
> Redirecting on this not founded page after succesful login.
> 
> ![image](https://user-images.githubusercontent.com/31833518/102628413-eb3d1900-4149-11eb-9698-11c0b3206d18.png)

**Comment by BenoitPoulet** [comment] 2020-12-29 09:41
Absolutely not the same problem.
I'm talking about ACL permission issue.

**Comment by BettaSplendensFR** [comment] 2020-12-30 15:06
> 
> 
> Resolved by changing _10-centreon.conf_
> Adding that to _<Directory "/usr/share/centreon/www">_
> 
> ```
> RewriteRule ^index\.html$ - [L]
> RewriteCond %{REQUEST_FILENAME} !-f
> RewriteCond %{REQUEST_FILENAME} !-d
> RewriteRule . /index.html [L]
> ErrorDocument 404 /centreon/index.html
> ```
It's not the same problem as OP refered, but I've got the same issue here, thanks a lot for your help, it worked perfectly ! I was shearching for while...

Sorry @BenoitPoulet , I can't help you, I just upgraded my Centreon from 20.04 to 20.10, and I can't reproduce the problem.
Might be a redirect problem ? Maybe the solution is the same kind of the one provided by @adonix-dev ?

**Closed** 2020-12-30 16:46 UTC
Labels: status/new

**Comment by Kevs308** [comment] 2021-03-04 12:48
Hello
it works for me on Centreon 20.10 for opened link to custom view.
Thank
