### ISSUE TITLE
[ACL] - Pb to view Host real downtime

### ISSUE THREAD

**Issue by cmeschin** [centreon/centreon#6102] opened 2018-03-01 13:03 UTC
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.16

**Centreon Engine version**: 1.8.1

**Centreon Broker version**: 3.0.11

**OS**: CentOS 6.9

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Have a user with ACL
2. Set a real downtime on a host and all his services,  visible by this user.
3. wait downtime is applied

**Describe the results you received:**
Downtime on host is not visible in downtime menu by this user, downtimes on services are visible.
So the user can't cancel the downtime on this host.

**Describe the results you expected:**
Downtime on host should be visible and should be able to be canceled
Currently, only admin user's can cancel these downtimes.

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by Moujimouja** [comment] 2020-06-05 15:30
Hi,

Can't reproduce in 19.10.x nor 20.04.x 

I close the issue.

**Closed by Moujimouja** 2020-06-05 15:30 UTC
Labels: area/acl, area/monitoring, kind/bug, priority/major

**Comment by cmeschin** [comment] 2020-06-19 15:41
Hi, I confirm it works on 19.10.
Thanks
