### ISSUE TITLE
Centreon Broker 3.0.5 - Issue

### ISSUE THREAD

**Issue by Tomszy** [centreon/centreon#5119] opened 2017-03-31 08:33 UTC
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:2.8.5 
**Centreon Engine version**:1.7.1 
**Centreon Broker version**:3.0.5 
**OS**: Oracle Linux 7
**Additional environment detail**s :Virtual
**Steps to reproduce the issue:**
1. We updated centreon to 2.8.5
2. We are getting the following errors in /var/log/centreon-broker/central-broker-master.log
3. " error: multiplexing: attempt to acknowledge more events than available central-broker-master-perfdata event queue: 84 requested, 83 acknowledged"

 
**Describe the results you received:**
We are getting many errors like this:
" error: multiplexing: attempt to acknowledge more events than available central-broker-master-perfdata event queue: 84 requested, 83 acknowledged"

**Describe the results you expected:**
We expect no errors.

![broker](https://cloud.githubusercontent.com/assets/25457811/24542829/7177b722-15fd-11e7-8ac2-938cf61e9798.PNG)

Any idea how to solve this?

Regards,

Tamas

**Comment by zskarman** [comment] 2017-03-31 10:57
Hi,
Is is an bug, or config issue?
Rgs, Zsolt

**Comment by hocinetwork** [comment] 2017-04-01 17:01
Hi

Same for me after 2.8.5 update and centreon-broker 3.0.5

<img width="1184" alt="capture d ecran 2017-04-01 a 18 56 40" src="https://cloud.githubusercontent.com/assets/22976562/24580736/714efed4-170d-11e7-85d4-7e0a51f8fb34.png">

**Comment by zskarman** [comment] 2017-04-03 07:39
Hi Guys,

Any news on this?
Rgs, Zsolt

**Comment by Sims24** [comment] 2017-04-12 11:25
Hi, 
You should open this in centreon-broker github I think.

**Comment by itsul** [comment] 2017-05-08 07:40
We could confirm this behavior too.

**Comment by ganoze** [comment] 2017-05-11 11:55
Duplicate of centreon/centreon-broker#93

**Closed by ganoze** 2017-05-11 11:55 UTC
Labels: Kind/Bug
