### ISSUE TITLE
SNMP Traps definition : values set to Linked Services and Linked service templates fields are not saved

### ISSUE THREAD

**Issue by thiuyendang** [centreon/centreon#5397] opened 2017-06-30 14:51 UTC
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.9

**Centreon Engine version**: 

**Centreon Broker version**: 

**OS**: CentOS6

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Add a SNMP trap definition
2. Set value to Linked Services and Linked service templates fields in Relations tab 
3. Save

**Describe the results you received:**
Fields are empty when we edit the record.

**Describe the results you expected:**
Values set to those fields have to be saved.

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment] 2017-07-06 14:11
duplicate of 5406

**Closed by lpinsivy** 2017-07-06 14:11 UTC
