### ISSUE TITLE
Hostgroups Summary does not display HG Alias

### ISSUE THREAD

**Issue by richardlawley** [centreon/centreon#6118] opened 2018-03-08 13:19 UTC
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.18

**Centreon Engine version**: 1.8.1

**Centreon Broker version**: 3.0.13

**OS**: CentOS 7.4 (up-to-date)

**Additional environment details (AWS, VirtualBox, physical, etc.):** Virtualbox

**Steps to reproduce the issue:**
1. Configuration > Hosts > Host Groups
2. Create a Host Group Name "test-hg" with Alias "Test Host Group"
3. Monitoring > Status Details > Hostgroups Summary

**Describe the results you received:**
Host Group column contains "test-hg (test-hg)"

**Describe the results you expected:**
Host Group column contains "test-hg (Test Host Group)"

**Additional information you think important (e.g. issue happens only occasionally):**
www/include/monitoring/status/HostGroups/xml/hostGroupXML.php contains a lookup table for id to alias, but it's being populated with id to id instead (line 68):

```
$convertTable[$hg["name"]] = $hg["name"];     // Presumably should be = $hg["alias"], but alias doesn't exist in centreon_storage.hostgroups
```

**Comment by lpinsivy** [comment] 2018-03-15 09:27
Duplicate of #5967

**Closed by lpinsivy** 2018-03-15 09:27 UTC

**Comment by richardlawley** [comment] 2018-03-15 09:33
In that case it would be sensible to change the display so it's not displaying the duplicated text: hgname (hgname)

**Comment by BenoitPoulet** [comment] 2018-03-15 09:35
In fact, Centreon do not manage Hostgroup Alias correctly. The alias is mandatory but the info is not really managed, even in the API. They must do something consistent.
