### ISSUE TITLE
Centreon dont looking for ACL on multiple LDAP

### ISSUE THREAD

**Issue by OpensourceMonitoringRepository** [centreon/centreon#6516] opened 2018-08-01 19:10 UTC
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
2.8.21
**Centreon Engine version**: 
1.8.1
**Centreon Broker version**: 
3.0.14
**OS**: 
Redhat 6.8
**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1.We have 2 LDAP
2. Some Users on ldap 1 and some on LDAP 2
3.we will create centreon groups on both LDAP
4. we dont have LDAP for both forest
5. we have approval relationship between LDAP

**Describe the results you received:**
1. fist LDAP answer for user
2. if user is not on fist LDAP centreon dont looking for groups on second LDAP

**Describe the results you expected:**
with multiple LDAP need looking for all LDAP groups for ACL

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment] 2018-08-21 11:45
Duplicate of #6238 ?

**Closed by lpinsivy** 2018-08-21 11:45 UTC
