### ISSUE TITLE
'Monitoring - Status Details - Hostgroups Summary' wrong data for ACL users 

### ISSUE THREAD

**Issue by bmareau** [centreon/centreon#6187] opened 2018-04-05 08:59 UTC
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**Centreon Web version**: 2.8.19
**Centreon Engine version**: 1.8.1
**Centreon Broker version**: 3.0.13

**Steps to reproduce the issue:**
1. Create user with ACL
2. Create Hostgroups
3. Connect with this user
4. 'Monitoring - Status Details - Hostgroups Summary' is wrong

**Describe the results you received:**
Total of hostgroups is not good

For admin user : 
![admin](https://user-images.githubusercontent.com/13255513/38356546-4f00d4b2-38c0-11e8-8562-9b37a61ce940.jpg)

For user with ACL : 
![acl](https://user-images.githubusercontent.com/13255513/38356550-52307d2c-38c0-11e8-9b18-a1f373527367.jpg)

Best Regards

**Comment by joviado** [comment] 2018-08-02 20:07
**Centreon Web version:** 2.8.24
**Centreon Engine version:** 1.8.1
**Centreon Broker version:** 3.0.14

The same problem

**Comment by Moujimouja** [comment] 2020-06-05 15:36
Hi,

Thanks for your feedback. 

I can't reproduce it on 19.10.x nor 20.04.x.

I close this issue

**Closed by Moujimouja** 2020-06-05 15:36 UTC
Labels: area/acl, area/monitoring, kind/bug, priority/minor
