### ISSUE TITLE
Number of rows in monitoring reverts to 30

### ISSUE THREAD

**Issue by btassite** [centreon/centreon#6325] opened 2018-05-29 14:01 UTC
Centreon version 2.8.22
Centreon Engine 1.8.1
Centreon Broker 3.0.14

Firefox 56/latest Chrome (currently 66, both Linux)

When you navigate around from Monitoring/Status Details/Services to Hosts to Performances/curves and back to Services or Hosts, the number of rows shown on screen keeps reverting to 30, even if you select 100 multiple times on each change (cookies/local storage are allowed). Administration, Parameters, Centreon UI, "Limit per page (default)" is set to 200, "Limit per page for monitoring" is set to 100 (same when you set the default to 100).

**Comment by lpinsivy** [comment] 2018-06-19 12:46
maybe linked to #5109

**Comment by Moujimouja** [comment] 2020-06-05 15:39
Hi,

Thanks for your feedback. 

I can't reproduce it on 19.10.x nor 20.04.x so I close this issue.

Have a nice evening

**Closed by Moujimouja** 2020-06-05 15:39 UTC
Labels: area/monitoring, kind/bug, priority/minor
