### ISSUE TITLE
Creating PNG in Monitoring > Performances > Graphs not working

### ISSUE THREAD

**Issue by salinger1** [centreon/centreon#6603] opened 2018-09-10 11:27 UTC
Hi,

downloading a png file from "Monitoring  >  Performances  >  Graphs" from any service is not working.
Centreon is creating a *.png file, but after download the created *.png file is about 1 Kilobyte small.
If I open it, any image editing tool says "Unknown File format, empty/damaged file or file not found".
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version 2.8.25: 

**Centreon Engine version 1.8.1: 

**Centreon Broker version 3.0.3: 

**OS**:  CentOS 7

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment] 2018-10-30 12:15
any error in /var/log/httpd/error.log or console JS?

works on ma 2.8.25

**Comment by adr-mo** [comment] 2019-04-25 14:26
**No answer now for 6 months.**

Futhermore the issue is not present neither on

- 2.8.27
- 18.10.4
- 19.04.0

Closing this issue.

Regards,

**Closed by adr-mo** 2019-04-25 14:26 UTC
Labels: status/more-info-needed
