### ISSUE TITLE
Change poller on graph 

### ISSUE THREAD

**Issue by lolokai** [centreon/centreon#5099] opened 2017-03-23 09:53 UTC
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 2.8.4

**Centreon Engine version**: 1.7.0

**Centreon Broker version**: 3.0

**OS**: Centreon 3.4

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VM

**Steps to reproduce the issue:**
1. Go to Home ==> Monitoring engine statistics
2. Click on Graphs (left menu)
3. Try to change poller

**Describe the results you received:**
It's impossible to change poller

**Describe the results you expected:**
Be able to change poller

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by lpinsivy** [comment] 2017-09-08 11:12
duplicate of #4954 and already corrected

**Closed by lpinsivy** 2017-09-08 11:12 UTC
